[package]
name = "moon_env"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "The moon store and workspace environment."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
miette = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
