approvedGitRepositories:
  - '**'

catalog:
  vite: 'npm:@voidzero-dev/vite-plus-core@0.2.1'
  vite-plus: 0.2.1

changesetIgnorePatterns:
  - '**/cjs/**/*'
  - '**/lib/**/*'
  - '**/mjs/**/*'
  - '**/*.test.{js,ts,tsx}'
  - '**/*.{md,mdx}'
  - website/**/*

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

enableTelemetry: false

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.16.0.cjs
