changesetIgnorePatterns:
  - '**/cjs/**/*'
  - '**/lib/**/*'
  - '**/mjs/**/*'
  - '**/*.test.{js,ts,tsx}'
  - '**/*.{md,mdx}'
  - website/**/*

compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmRegistryServer: https://registry.npmjs.org

yarnPath: .yarn/releases/yarn-4.12.0.cjs
