changesetIgnorePatterns:
  - '**/cjs/**/*'
  - '**/lib/**/*'
  - '**/mjs/**/*'
  - '**/*.test.{js,ts,tsx}'
  - '**/*.{md,mdx}'
  - website/**/*

compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAuthToken: 23F99634-A6B0-4362-BB2B-7163253D741D
    npmRegistryServer: 'https://npm.fontawesome.com'

yarnPath: .yarn/releases/yarn-4.0.0.cjs
