[config]
default_to_workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--emit=files"]

[tasks.lint]
install_crate = "rustfmt"
command = "cargo"
args = ["clippy", "--workspace", "--all-targets"]
dependencies = ["format"]

[tasks.test-setup]
command = "cargo"
args = ["run", "--", "setup"]
env = { MOON_NODE_VERSION = "16.0.0" }

[tasks.test]
command = "cargo"
args = ["test", "--workspace"]
dependencies = ["test-setup"]

[tasks.test-output]
command = "cargo"
args = ["test", "--workspace", "--", "--nocapture", "--show-output"]
dependencies = ["test-setup"]

[tasks.gen-json-schemas]
command = "cargo"
args = ["run", "-p", "moon_config"]

[tasks.check]
dependencies = [
    "format",
    "build",
    "test"
]

