import { defineConfig } from "vite-plus";

export default defineConfig({
  lint: {
    "plugins": [
      "oxc",
      "typescript",
      "unicorn",
      "react",
      "promise",
      "import",
      "node"
    ],
    "jsPlugins": [
      {
        "name": "vite-plus",
        "specifier": "vite-plus/oxlint-plugin"
      }
    ],
    "categories": {
      "correctness": "warn"
    },
    "options": {
      "typeAware": true,
      "typeCheck": true
    },
    "env": {
      "builtin": true,
      "commonjs": true
    },
    "globals": {
      "AbortController": "readonly",
      "AbortSignal": "readonly",
      "AbsoluteOrientationSensor": "readonly",
      "AbstractRange": "readonly",
      "Accelerometer": "readonly",
      "addEventListener": "readonly",
      "ai": "readonly",
      "AI": "readonly",
      "AITextSession": "readonly",
      "alert": "readonly",
      "AnalyserNode": "readonly",
      "Animation": "readonly",
      "AnimationEffect": "readonly",
      "AnimationEvent": "readonly",
      "AnimationPlaybackEvent": "readonly",
      "AnimationTimeline": "readonly",
      "atob": "readonly",
      "Attr": "readonly",
      "Audio": "readonly",
      "AudioBuffer": "readonly",
      "AudioBufferSourceNode": "readonly",
      "AudioContext": "readonly",
      "AudioData": "readonly",
      "AudioDecoder": "readonly",
      "AudioDestinationNode": "readonly",
      "AudioEncoder": "readonly",
      "AudioListener": "readonly",
      "AudioNode": "readonly",
      "AudioParam": "readonly",
      "AudioParamMap": "readonly",
      "AudioProcessingEvent": "readonly",
      "AudioScheduledSourceNode": "readonly",
      "AudioSinkInfo": "readonly",
      "AudioWorklet": "readonly",
      "AudioWorkletGlobalScope": "readonly",
      "AudioWorkletNode": "readonly",
      "AudioWorkletProcessor": "readonly",
      "AuthenticatorAssertionResponse": "readonly",
      "AuthenticatorAttestationResponse": "readonly",
      "AuthenticatorResponse": "readonly",
      "BackgroundFetchManager": "readonly",
      "BackgroundFetchRecord": "readonly",
      "BackgroundFetchRegistration": "readonly",
      "BarcodeDetector": "readonly",
      "BarProp": "readonly",
      "BaseAudioContext": "readonly",
      "BatteryManager": "readonly",
      "BeforeUnloadEvent": "readonly",
      "BiquadFilterNode": "readonly",
      "Blob": "readonly",
      "BlobEvent": "readonly",
      "Bluetooth": "readonly",
      "BluetoothCharacteristicProperties": "readonly",
      "BluetoothDevice": "readonly",
      "BluetoothRemoteGATTCharacteristic": "readonly",
      "BluetoothRemoteGATTDescriptor": "readonly",
      "BluetoothRemoteGATTServer": "readonly",
      "BluetoothRemoteGATTService": "readonly",
      "BluetoothUUID": "readonly",
      "blur": "readonly",
      "BroadcastChannel": "readonly",
      "BrowserCaptureMediaStreamTrack": "readonly",
      "btoa": "readonly",
      "ByteLengthQueuingStrategy": "readonly",
      "Cache": "readonly",
      "caches": "readonly",
      "CacheStorage": "readonly",
      "cancelAnimationFrame": "readonly",
      "cancelIdleCallback": "readonly",
      "CanvasCaptureMediaStream": "readonly",
      "CanvasCaptureMediaStreamTrack": "readonly",
      "CanvasGradient": "readonly",
      "CanvasPattern": "readonly",
      "CanvasRenderingContext2D": "readonly",
      "CaptureController": "readonly",
      "CaretPosition": "readonly",
      "CDATASection": "readonly",
      "ChannelMergerNode": "readonly",
      "ChannelSplitterNode": "readonly",
      "ChapterInformation": "readonly",
      "CharacterBoundsUpdateEvent": "readonly",
      "CharacterData": "readonly",
      "clearInterval": "readonly",
      "clearTimeout": "readonly",
      "clientInformation": "readonly",
      "Clipboard": "readonly",
      "ClipboardEvent": "readonly",
      "ClipboardItem": "readonly",
      "close": "readonly",
      "closed": "readonly",
      "CloseEvent": "readonly",
      "CloseWatcher": "readonly",
      "Comment": "readonly",
      "CompositionEvent": "readonly",
      "CompressionStream": "readonly",
      "confirm": "readonly",
      "console": "readonly",
      "ConstantSourceNode": "readonly",
      "ContentVisibilityAutoStateChangeEvent": "readonly",
      "ConvolverNode": "readonly",
      "CookieChangeEvent": "readonly",
      "CookieDeprecationLabel": "readonly",
      "cookieStore": "readonly",
      "CookieStore": "readonly",
      "CookieStoreManager": "readonly",
      "CountQueuingStrategy": "readonly",
      "createImageBitmap": "readonly",
      "Credential": "readonly",
      "credentialless": "readonly",
      "CredentialsContainer": "readonly",
      "CropTarget": "readonly",
      "crossOriginIsolated": "readonly",
      "crypto": "readonly",
      "Crypto": "readonly",
      "CryptoKey": "readonly",
      "CSS": "readonly",
      "CSSAnimation": "readonly",
      "CSSConditionRule": "readonly",
      "CSSContainerRule": "readonly",
      "CSSCounterStyleRule": "readonly",
      "CSSFontFaceRule": "readonly",
      "CSSFontFeatureValuesRule": "readonly",
      "CSSFontPaletteValuesRule": "readonly",
      "CSSGroupingRule": "readonly",
      "CSSImageValue": "readonly",
      "CSSImportRule": "readonly",
      "CSSKeyframeRule": "readonly",
      "CSSKeyframesRule": "readonly",
      "CSSKeywordValue": "readonly",
      "CSSLayerBlockRule": "readonly",
      "CSSLayerStatementRule": "readonly",
      "CSSMarginRule": "readonly",
      "CSSMathClamp": "readonly",
      "CSSMathInvert": "readonly",
      "CSSMathMax": "readonly",
      "CSSMathMin": "readonly",
      "CSSMathNegate": "readonly",
      "CSSMathProduct": "readonly",
      "CSSMathSum": "readonly",
      "CSSMathValue": "readonly",
      "CSSMatrixComponent": "readonly",
      "CSSMediaRule": "readonly",
      "CSSNamespaceRule": "readonly",
      "CSSNestedDeclarations": "readonly",
      "CSSNumericArray": "readonly",
      "CSSNumericValue": "readonly",
      "CSSPageDescriptors": "readonly",
      "CSSPageRule": "readonly",
      "CSSPerspective": "readonly",
      "CSSPositionTryDescriptors": "readonly",
      "CSSPositionTryRule": "readonly",
      "CSSPositionValue": "readonly",
      "CSSPropertyRule": "readonly",
      "CSSRotate": "readonly",
      "CSSRule": "readonly",
      "CSSRuleList": "readonly",
      "CSSScale": "readonly",
      "CSSScopeRule": "readonly",
      "CSSSkew": "readonly",
      "CSSSkewX": "readonly",
      "CSSSkewY": "readonly",
      "CSSStartingStyleRule": "readonly",
      "CSSStyleDeclaration": "readonly",
      "CSSStyleRule": "readonly",
      "CSSStyleSheet": "readonly",
      "CSSStyleValue": "readonly",
      "CSSSupportsRule": "readonly",
      "CSSTransformComponent": "readonly",
      "CSSTransformValue": "readonly",
      "CSSTransition": "readonly",
      "CSSTranslate": "readonly",
      "CSSUnitValue": "readonly",
      "CSSUnparsedValue": "readonly",
      "CSSVariableReferenceValue": "readonly",
      "CSSViewTransitionRule": "readonly",
      "currentFrame": "readonly",
      "currentTime": "readonly",
      "CustomElementRegistry": "readonly",
      "customElements": "readonly",
      "CustomEvent": "readonly",
      "CustomStateSet": "readonly",
      "DataTransfer": "readonly",
      "DataTransferItem": "readonly",
      "DataTransferItemList": "readonly",
      "DecompressionStream": "readonly",
      "DelayNode": "readonly",
      "DelegatedInkTrailPresenter": "readonly",
      "DeviceMotionEvent": "readonly",
      "DeviceMotionEventAcceleration": "readonly",
      "DeviceMotionEventRotationRate": "readonly",
      "DeviceOrientationEvent": "readonly",
      "devicePixelRatio": "readonly",
      "dispatchEvent": "readonly",
      "document": "readonly",
      "Document": "readonly",
      "DocumentFragment": "readonly",
      "documentPictureInPicture": "readonly",
      "DocumentPictureInPicture": "readonly",
      "DocumentPictureInPictureEvent": "readonly",
      "DocumentTimeline": "readonly",
      "DocumentType": "readonly",
      "DOMError": "readonly",
      "DOMException": "readonly",
      "DOMImplementation": "readonly",
      "DOMMatrix": "readonly",
      "DOMMatrixReadOnly": "readonly",
      "DOMParser": "readonly",
      "DOMPoint": "readonly",
      "DOMPointReadOnly": "readonly",
      "DOMQuad": "readonly",
      "DOMRect": "readonly",
      "DOMRectList": "readonly",
      "DOMRectReadOnly": "readonly",
      "DOMStringList": "readonly",
      "DOMStringMap": "readonly",
      "DOMTokenList": "readonly",
      "DragEvent": "readonly",
      "DynamicsCompressorNode": "readonly",
      "EditContext": "readonly",
      "Element": "readonly",
      "ElementInternals": "readonly",
      "EncodedAudioChunk": "readonly",
      "EncodedVideoChunk": "readonly",
      "ErrorEvent": "readonly",
      "event": "readonly",
      "Event": "readonly",
      "EventCounts": "readonly",
      "EventSource": "readonly",
      "EventTarget": "readonly",
      "external": "readonly",
      "External": "readonly",
      "EyeDropper": "readonly",
      "FeaturePolicy": "readonly",
      "FederatedCredential": "readonly",
      "fence": "readonly",
      "Fence": "readonly",
      "FencedFrameConfig": "readonly",
      "fetch": "readonly",
      "fetchLater": "readonly",
      "FetchLaterResult": "readonly",
      "File": "readonly",
      "FileList": "readonly",
      "FileReader": "readonly",
      "FileSystem": "readonly",
      "FileSystemDirectoryEntry": "readonly",
      "FileSystemDirectoryHandle": "readonly",
      "FileSystemDirectoryReader": "readonly",
      "FileSystemEntry": "readonly",
      "FileSystemFileEntry": "readonly",
      "FileSystemFileHandle": "readonly",
      "FileSystemHandle": "readonly",
      "FileSystemWritableFileStream": "readonly",
      "find": "readonly",
      "focus": "readonly",
      "FocusEvent": "readonly",
      "FontData": "readonly",
      "FontFace": "readonly",
      "FontFaceSet": "readonly",
      "FontFaceSetLoadEvent": "readonly",
      "FormData": "readonly",
      "FormDataEvent": "readonly",
      "FragmentDirective": "readonly",
      "frameElement": "readonly",
      "frames": "readonly",
      "GainNode": "readonly",
      "Gamepad": "readonly",
      "GamepadAxisMoveEvent": "readonly",
      "GamepadButton": "readonly",
      "GamepadButtonEvent": "readonly",
      "GamepadEvent": "readonly",
      "GamepadHapticActuator": "readonly",
      "GamepadPose": "readonly",
      "Geolocation": "readonly",
      "GeolocationCoordinates": "readonly",
      "GeolocationPosition": "readonly",
      "GeolocationPositionError": "readonly",
      "getComputedStyle": "readonly",
      "getScreenDetails": "readonly",
      "getSelection": "readonly",
      "GPU": "readonly",
      "GPUAdapter": "readonly",
      "GPUAdapterInfo": "readonly",
      "GPUBindGroup": "readonly",
      "GPUBindGroupLayout": "readonly",
      "GPUBuffer": "readonly",
      "GPUBufferUsage": "readonly",
      "GPUCanvasContext": "readonly",
      "GPUColorWrite": "readonly",
      "GPUCommandBuffer": "readonly",
      "GPUCommandEncoder": "readonly",
      "GPUCompilationInfo": "readonly",
      "GPUCompilationMessage": "readonly",
      "GPUComputePassEncoder": "readonly",
      "GPUComputePipeline": "readonly",
      "GPUDevice": "readonly",
      "GPUDeviceLostInfo": "readonly",
      "GPUError": "readonly",
      "GPUExternalTexture": "readonly",
      "GPUInternalError": "readonly",
      "GPUMapMode": "readonly",
      "GPUOutOfMemoryError": "readonly",
      "GPUPipelineError": "readonly",
      "GPUPipelineLayout": "readonly",
      "GPUQuerySet": "readonly",
      "GPUQueue": "readonly",
      "GPURenderBundle": "readonly",
      "GPURenderBundleEncoder": "readonly",
      "GPURenderPassEncoder": "readonly",
      "GPURenderPipeline": "readonly",
      "GPUSampler": "readonly",
      "GPUShaderModule": "readonly",
      "GPUShaderStage": "readonly",
      "GPUSupportedFeatures": "readonly",
      "GPUSupportedLimits": "readonly",
      "GPUTexture": "readonly",
      "GPUTextureUsage": "readonly",
      "GPUTextureView": "readonly",
      "GPUUncapturedErrorEvent": "readonly",
      "GPUValidationError": "readonly",
      "GravitySensor": "readonly",
      "Gyroscope": "readonly",
      "HashChangeEvent": "readonly",
      "Headers": "readonly",
      "HID": "readonly",
      "HIDConnectionEvent": "readonly",
      "HIDDevice": "readonly",
      "HIDInputReportEvent": "readonly",
      "Highlight": "readonly",
      "HighlightRegistry": "readonly",
      "history": "readonly",
      "History": "readonly",
      "HTMLAllCollection": "readonly",
      "HTMLAnchorElement": "readonly",
      "HTMLAreaElement": "readonly",
      "HTMLAudioElement": "readonly",
      "HTMLBaseElement": "readonly",
      "HTMLBodyElement": "readonly",
      "HTMLBRElement": "readonly",
      "HTMLButtonElement": "readonly",
      "HTMLCanvasElement": "readonly",
      "HTMLCollection": "readonly",
      "HTMLDataElement": "readonly",
      "HTMLDataListElement": "readonly",
      "HTMLDetailsElement": "readonly",
      "HTMLDialogElement": "readonly",
      "HTMLDirectoryElement": "readonly",
      "HTMLDivElement": "readonly",
      "HTMLDListElement": "readonly",
      "HTMLDocument": "readonly",
      "HTMLElement": "readonly",
      "HTMLEmbedElement": "readonly",
      "HTMLFencedFrameElement": "readonly",
      "HTMLFieldSetElement": "readonly",
      "HTMLFontElement": "readonly",
      "HTMLFormControlsCollection": "readonly",
      "HTMLFormElement": "readonly",
      "HTMLFrameElement": "readonly",
      "HTMLFrameSetElement": "readonly",
      "HTMLHeadElement": "readonly",
      "HTMLHeadingElement": "readonly",
      "HTMLHRElement": "readonly",
      "HTMLHtmlElement": "readonly",
      "HTMLIFrameElement": "readonly",
      "HTMLImageElement": "readonly",
      "HTMLInputElement": "readonly",
      "HTMLLabelElement": "readonly",
      "HTMLLegendElement": "readonly",
      "HTMLLIElement": "readonly",
      "HTMLLinkElement": "readonly",
      "HTMLMapElement": "readonly",
      "HTMLMarqueeElement": "readonly",
      "HTMLMediaElement": "readonly",
      "HTMLMenuElement": "readonly",
      "HTMLMetaElement": "readonly",
      "HTMLMeterElement": "readonly",
      "HTMLModElement": "readonly",
      "HTMLObjectElement": "readonly",
      "HTMLOListElement": "readonly",
      "HTMLOptGroupElement": "readonly",
      "HTMLOptionElement": "readonly",
      "HTMLOptionsCollection": "readonly",
      "HTMLOutputElement": "readonly",
      "HTMLParagraphElement": "readonly",
      "HTMLParamElement": "readonly",
      "HTMLPictureElement": "readonly",
      "HTMLPreElement": "readonly",
      "HTMLProgressElement": "readonly",
      "HTMLQuoteElement": "readonly",
      "HTMLScriptElement": "readonly",
      "HTMLSelectElement": "readonly",
      "HTMLSlotElement": "readonly",
      "HTMLSourceElement": "readonly",
      "HTMLSpanElement": "readonly",
      "HTMLStyleElement": "readonly",
      "HTMLTableCaptionElement": "readonly",
      "HTMLTableCellElement": "readonly",
      "HTMLTableColElement": "readonly",
      "HTMLTableElement": "readonly",
      "HTMLTableRowElement": "readonly",
      "HTMLTableSectionElement": "readonly",
      "HTMLTemplateElement": "readonly",
      "HTMLTextAreaElement": "readonly",
      "HTMLTimeElement": "readonly",
      "HTMLTitleElement": "readonly",
      "HTMLTrackElement": "readonly",
      "HTMLUListElement": "readonly",
      "HTMLUnknownElement": "readonly",
      "HTMLVideoElement": "readonly",
      "IDBCursor": "readonly",
      "IDBCursorWithValue": "readonly",
      "IDBDatabase": "readonly",
      "IDBFactory": "readonly",
      "IDBIndex": "readonly",
      "IDBKeyRange": "readonly",
      "IDBObjectStore": "readonly",
      "IDBOpenDBRequest": "readonly",
      "IDBRequest": "readonly",
      "IDBTransaction": "readonly",
      "IDBVersionChangeEvent": "readonly",
      "IdentityCredential": "readonly",
      "IdentityCredentialError": "readonly",
      "IdentityProvider": "readonly",
      "IdleDeadline": "readonly",
      "IdleDetector": "readonly",
      "IIRFilterNode": "readonly",
      "Image": "readonly",
      "ImageBitmap": "readonly",
      "ImageBitmapRenderingContext": "readonly",
      "ImageCapture": "readonly",
      "ImageData": "readonly",
      "ImageDecoder": "readonly",
      "ImageTrack": "readonly",
      "ImageTrackList": "readonly",
      "indexedDB": "readonly",
      "Ink": "readonly",
      "innerHeight": "readonly",
      "innerWidth": "readonly",
      "InputDeviceCapabilities": "readonly",
      "InputDeviceInfo": "readonly",
      "InputEvent": "readonly",
      "IntersectionObserver": "readonly",
      "IntersectionObserverEntry": "readonly",
      "isSecureContext": "readonly",
      "Keyboard": "readonly",
      "KeyboardEvent": "readonly",
      "KeyboardLayoutMap": "readonly",
      "KeyframeEffect": "readonly",
      "LargestContentfulPaint": "readonly",
      "LaunchParams": "readonly",
      "launchQueue": "readonly",
      "LaunchQueue": "readonly",
      "LayoutShift": "readonly",
      "LayoutShiftAttribution": "readonly",
      "length": "readonly",
      "LinearAccelerationSensor": "readonly",
      "localStorage": "readonly",
      "location": "writable",
      "Location": "readonly",
      "locationbar": "readonly",
      "Lock": "readonly",
      "LockManager": "readonly",
      "matchMedia": "readonly",
      "MathMLElement": "readonly",
      "MediaCapabilities": "readonly",
      "MediaCapabilitiesInfo": "readonly",
      "MediaDeviceInfo": "readonly",
      "MediaDevices": "readonly",
      "MediaElementAudioSourceNode": "readonly",
      "MediaEncryptedEvent": "readonly",
      "MediaError": "readonly",
      "MediaKeyError": "readonly",
      "MediaKeyMessageEvent": "readonly",
      "MediaKeys": "readonly",
      "MediaKeySession": "readonly",
      "MediaKeyStatusMap": "readonly",
      "MediaKeySystemAccess": "readonly",
      "MediaList": "readonly",
      "MediaMetadata": "readonly",
      "MediaQueryList": "readonly",
      "MediaQueryListEvent": "readonly",
      "MediaRecorder": "readonly",
      "MediaRecorderErrorEvent": "readonly",
      "MediaSession": "readonly",
      "MediaSource": "readonly",
      "MediaSourceHandle": "readonly",
      "MediaStream": "readonly",
      "MediaStreamAudioDestinationNode": "readonly",
      "MediaStreamAudioSourceNode": "readonly",
      "MediaStreamEvent": "readonly",
      "MediaStreamTrack": "readonly",
      "MediaStreamTrackAudioSourceNode": "readonly",
      "MediaStreamTrackAudioStats": "readonly",
      "MediaStreamTrackEvent": "readonly",
      "MediaStreamTrackGenerator": "readonly",
      "MediaStreamTrackProcessor": "readonly",
      "MediaStreamTrackVideoStats": "readonly",
      "menubar": "readonly",
      "MessageChannel": "readonly",
      "MessageEvent": "readonly",
      "MessagePort": "readonly",
      "MIDIAccess": "readonly",
      "MIDIConnectionEvent": "readonly",
      "MIDIInput": "readonly",
      "MIDIInputMap": "readonly",
      "MIDIMessageEvent": "readonly",
      "MIDIOutput": "readonly",
      "MIDIOutputMap": "readonly",
      "MIDIPort": "readonly",
      "MimeType": "readonly",
      "MimeTypeArray": "readonly",
      "model": "readonly",
      "ModelGenericSession": "readonly",
      "ModelManager": "readonly",
      "MouseEvent": "readonly",
      "moveBy": "readonly",
      "moveTo": "readonly",
      "MutationEvent": "readonly",
      "MutationObserver": "readonly",
      "MutationRecord": "readonly",
      "name": "readonly",
      "NamedNodeMap": "readonly",
      "NavigateEvent": "readonly",
      "navigation": "readonly",
      "Navigation": "readonly",
      "NavigationActivation": "readonly",
      "NavigationCurrentEntryChangeEvent": "readonly",
      "NavigationDestination": "readonly",
      "NavigationHistoryEntry": "readonly",
      "NavigationPreloadManager": "readonly",
      "NavigationTransition": "readonly",
      "navigator": "readonly",
      "Navigator": "readonly",
      "NavigatorLogin": "readonly",
      "NavigatorManagedData": "readonly",
      "NavigatorUAData": "readonly",
      "NetworkInformation": "readonly",
      "Node": "readonly",
      "NodeFilter": "readonly",
      "NodeIterator": "readonly",
      "NodeList": "readonly",
      "Notification": "readonly",
      "NotifyPaintEvent": "readonly",
      "NotRestoredReasonDetails": "readonly",
      "NotRestoredReasons": "readonly",
      "OfflineAudioCompletionEvent": "readonly",
      "OfflineAudioContext": "readonly",
      "offscreenBuffering": "readonly",
      "OffscreenCanvas": "readonly",
      "OffscreenCanvasRenderingContext2D": "readonly",
      "onabort": "writable",
      "onafterprint": "writable",
      "onanimationcancel": "writable",
      "onanimationend": "writable",
      "onanimationiteration": "writable",
      "onanimationstart": "writable",
      "onappinstalled": "writable",
      "onauxclick": "writable",
      "onbeforeinput": "writable",
      "onbeforeinstallprompt": "writable",
      "onbeforematch": "writable",
      "onbeforeprint": "writable",
      "onbeforetoggle": "writable",
      "onbeforeunload": "writable",
      "onbeforexrselect": "writable",
      "onblur": "writable",
      "oncancel": "writable",
      "oncanplay": "writable",
      "oncanplaythrough": "writable",
      "onchange": "writable",
      "onclick": "writable",
      "onclose": "writable",
      "oncontentvisibilityautostatechange": "writable",
      "oncontextlost": "writable",
      "oncontextmenu": "writable",
      "oncontextrestored": "writable",
      "oncopy": "writable",
      "oncuechange": "writable",
      "oncut": "writable",
      "ondblclick": "writable",
      "ondevicemotion": "writable",
      "ondeviceorientation": "writable",
      "ondeviceorientationabsolute": "writable",
      "ondrag": "writable",
      "ondragend": "writable",
      "ondragenter": "writable",
      "ondragleave": "writable",
      "ondragover": "writable",
      "ondragstart": "writable",
      "ondrop": "writable",
      "ondurationchange": "writable",
      "onemptied": "writable",
      "onended": "writable",
      "onerror": "writable",
      "onfocus": "writable",
      "onformdata": "writable",
      "ongamepadconnected": "writable",
      "ongamepaddisconnected": "writable",
      "ongotpointercapture": "writable",
      "onhashchange": "writable",
      "oninput": "writable",
      "oninvalid": "writable",
      "onkeydown": "writable",
      "onkeypress": "writable",
      "onkeyup": "writable",
      "onlanguagechange": "writable",
      "onload": "writable",
      "onloadeddata": "writable",
      "onloadedmetadata": "writable",
      "onloadstart": "writable",
      "onlostpointercapture": "writable",
      "onmessage": "writable",
      "onmessageerror": "writable",
      "onmousedown": "writable",
      "onmouseenter": "writable",
      "onmouseleave": "writable",
      "onmousemove": "writable",
      "onmouseout": "writable",
      "onmouseover": "writable",
      "onmouseup": "writable",
      "onmousewheel": "writable",
      "onoffline": "writable",
      "ononline": "writable",
      "onpagehide": "writable",
      "onpagereveal": "writable",
      "onpageshow": "writable",
      "onpageswap": "writable",
      "onpaste": "writable",
      "onpause": "writable",
      "onplay": "writable",
      "onplaying": "writable",
      "onpointercancel": "writable",
      "onpointerdown": "writable",
      "onpointerenter": "writable",
      "onpointerleave": "writable",
      "onpointermove": "writable",
      "onpointerout": "writable",
      "onpointerover": "writable",
      "onpointerrawupdate": "writable",
      "onpointerup": "writable",
      "onpopstate": "writable",
      "onprogress": "writable",
      "onratechange": "writable",
      "onrejectionhandled": "writable",
      "onreset": "writable",
      "onresize": "writable",
      "onscroll": "writable",
      "onscrollend": "writable",
      "onscrollsnapchange": "writable",
      "onscrollsnapchanging": "writable",
      "onsearch": "writable",
      "onsecuritypolicyviolation": "writable",
      "onseeked": "writable",
      "onseeking": "writable",
      "onselect": "writable",
      "onselectionchange": "writable",
      "onselectstart": "writable",
      "onslotchange": "writable",
      "onstalled": "writable",
      "onstorage": "writable",
      "onsubmit": "writable",
      "onsuspend": "writable",
      "ontimeupdate": "writable",
      "ontoggle": "writable",
      "ontransitioncancel": "writable",
      "ontransitionend": "writable",
      "ontransitionrun": "writable",
      "ontransitionstart": "writable",
      "onunhandledrejection": "writable",
      "onunload": "writable",
      "onvolumechange": "writable",
      "onwaiting": "writable",
      "onwheel": "writable",
      "open": "readonly",
      "opener": "readonly",
      "Option": "readonly",
      "OrientationSensor": "readonly",
      "origin": "readonly",
      "originAgentCluster": "readonly",
      "OscillatorNode": "readonly",
      "OTPCredential": "readonly",
      "outerHeight": "readonly",
      "outerWidth": "readonly",
      "OverconstrainedError": "readonly",
      "PageRevealEvent": "readonly",
      "PageSwapEvent": "readonly",
      "PageTransitionEvent": "readonly",
      "pageXOffset": "readonly",
      "pageYOffset": "readonly",
      "PannerNode": "readonly",
      "parent": "readonly",
      "PasswordCredential": "readonly",
      "Path2D": "readonly",
      "PaymentAddress": "readonly",
      "PaymentManager": "readonly",
      "PaymentMethodChangeEvent": "readonly",
      "PaymentRequest": "readonly",
      "PaymentRequestUpdateEvent": "readonly",
      "PaymentResponse": "readonly",
      "performance": "readonly",
      "Performance": "readonly",
      "PerformanceElementTiming": "readonly",
      "PerformanceEntry": "readonly",
      "PerformanceEventTiming": "readonly",
      "PerformanceLongAnimationFrameTiming": "readonly",
      "PerformanceLongTaskTiming": "readonly",
      "PerformanceMark": "readonly",
      "PerformanceMeasure": "readonly",
      "PerformanceNavigation": "readonly",
      "PerformanceNavigationTiming": "readonly",
      "PerformanceObserver": "readonly",
      "PerformanceObserverEntryList": "readonly",
      "PerformancePaintTiming": "readonly",
      "PerformanceResourceTiming": "readonly",
      "PerformanceScriptTiming": "readonly",
      "PerformanceServerTiming": "readonly",
      "PerformanceTiming": "readonly",
      "PeriodicSyncManager": "readonly",
      "PeriodicWave": "readonly",
      "Permissions": "readonly",
      "PermissionStatus": "readonly",
      "PERSISTENT": "readonly",
      "personalbar": "readonly",
      "PictureInPictureEvent": "readonly",
      "PictureInPictureWindow": "readonly",
      "Plugin": "readonly",
      "PluginArray": "readonly",
      "PointerEvent": "readonly",
      "PopStateEvent": "readonly",
      "postMessage": "readonly",
      "Presentation": "readonly",
      "PresentationAvailability": "readonly",
      "PresentationConnection": "readonly",
      "PresentationConnectionAvailableEvent": "readonly",
      "PresentationConnectionCloseEvent": "readonly",
      "PresentationConnectionList": "readonly",
      "PresentationReceiver": "readonly",
      "PresentationRequest": "readonly",
      "PressureObserver": "readonly",
      "PressureRecord": "readonly",
      "print": "readonly",
      "ProcessingInstruction": "readonly",
      "Profiler": "readonly",
      "ProgressEvent": "readonly",
      "PromiseRejectionEvent": "readonly",
      "prompt": "readonly",
      "ProtectedAudience": "readonly",
      "PublicKeyCredential": "readonly",
      "PushManager": "readonly",
      "PushSubscription": "readonly",
      "PushSubscriptionOptions": "readonly",
      "queryLocalFonts": "readonly",
      "queueMicrotask": "readonly",
      "RadioNodeList": "readonly",
      "Range": "readonly",
      "ReadableByteStreamController": "readonly",
      "ReadableStream": "readonly",
      "ReadableStreamBYOBReader": "readonly",
      "ReadableStreamBYOBRequest": "readonly",
      "ReadableStreamDefaultController": "readonly",
      "ReadableStreamDefaultReader": "readonly",
      "registerProcessor": "readonly",
      "RelativeOrientationSensor": "readonly",
      "RemotePlayback": "readonly",
      "removeEventListener": "readonly",
      "reportError": "readonly",
      "ReportingObserver": "readonly",
      "Request": "readonly",
      "requestAnimationFrame": "readonly",
      "requestIdleCallback": "readonly",
      "resizeBy": "readonly",
      "ResizeObserver": "readonly",
      "ResizeObserverEntry": "readonly",
      "ResizeObserverSize": "readonly",
      "resizeTo": "readonly",
      "Response": "readonly",
      "RTCCertificate": "readonly",
      "RTCDataChannel": "readonly",
      "RTCDataChannelEvent": "readonly",
      "RTCDtlsTransport": "readonly",
      "RTCDTMFSender": "readonly",
      "RTCDTMFToneChangeEvent": "readonly",
      "RTCEncodedAudioFrame": "readonly",
      "RTCEncodedVideoFrame": "readonly",
      "RTCError": "readonly",
      "RTCErrorEvent": "readonly",
      "RTCIceCandidate": "readonly",
      "RTCIceTransport": "readonly",
      "RTCPeerConnection": "readonly",
      "RTCPeerConnectionIceErrorEvent": "readonly",
      "RTCPeerConnectionIceEvent": "readonly",
      "RTCRtpReceiver": "readonly",
      "RTCRtpScriptTransform": "readonly",
      "RTCRtpSender": "readonly",
      "RTCRtpTransceiver": "readonly",
      "RTCSctpTransport": "readonly",
      "RTCSessionDescription": "readonly",
      "RTCStatsReport": "readonly",
      "RTCTrackEvent": "readonly",
      "sampleRate": "readonly",
      "scheduler": "readonly",
      "Scheduler": "readonly",
      "Scheduling": "readonly",
      "screen": "readonly",
      "Screen": "readonly",
      "ScreenDetailed": "readonly",
      "ScreenDetails": "readonly",
      "screenLeft": "readonly",
      "ScreenOrientation": "readonly",
      "screenTop": "readonly",
      "screenX": "readonly",
      "screenY": "readonly",
      "ScriptProcessorNode": "readonly",
      "scroll": "readonly",
      "scrollbars": "readonly",
      "scrollBy": "readonly",
      "ScrollTimeline": "readonly",
      "scrollTo": "readonly",
      "scrollX": "readonly",
      "scrollY": "readonly",
      "SecurityPolicyViolationEvent": "readonly",
      "Selection": "readonly",
      "self": "readonly",
      "Sensor": "readonly",
      "SensorErrorEvent": "readonly",
      "Serial": "readonly",
      "SerialPort": "readonly",
      "ServiceWorker": "readonly",
      "ServiceWorkerContainer": "readonly",
      "ServiceWorkerRegistration": "readonly",
      "sessionStorage": "readonly",
      "setInterval": "readonly",
      "setTimeout": "readonly",
      "ShadowRoot": "readonly",
      "sharedStorage": "readonly",
      "SharedStorage": "readonly",
      "SharedStorageWorklet": "readonly",
      "SharedWorker": "readonly",
      "showDirectoryPicker": "readonly",
      "showOpenFilePicker": "readonly",
      "showSaveFilePicker": "readonly",
      "SnapEvent": "readonly",
      "SourceBuffer": "readonly",
      "SourceBufferList": "readonly",
      "speechSynthesis": "readonly",
      "SpeechSynthesis": "readonly",
      "SpeechSynthesisErrorEvent": "readonly",
      "SpeechSynthesisEvent": "readonly",
      "SpeechSynthesisUtterance": "readonly",
      "SpeechSynthesisVoice": "readonly",
      "StaticRange": "readonly",
      "status": "readonly",
      "statusbar": "readonly",
      "StereoPannerNode": "readonly",
      "stop": "readonly",
      "Storage": "readonly",
      "StorageBucket": "readonly",
      "StorageBucketManager": "readonly",
      "StorageEvent": "readonly",
      "StorageManager": "readonly",
      "structuredClone": "readonly",
      "styleMedia": "readonly",
      "StylePropertyMap": "readonly",
      "StylePropertyMapReadOnly": "readonly",
      "StyleSheet": "readonly",
      "StyleSheetList": "readonly",
      "SubmitEvent": "readonly",
      "SubtleCrypto": "readonly",
      "SVGAElement": "readonly",
      "SVGAngle": "readonly",
      "SVGAnimatedAngle": "readonly",
      "SVGAnimatedBoolean": "readonly",
      "SVGAnimatedEnumeration": "readonly",
      "SVGAnimatedInteger": "readonly",
      "SVGAnimatedLength": "readonly",
      "SVGAnimatedLengthList": "readonly",
      "SVGAnimatedNumber": "readonly",
      "SVGAnimatedNumberList": "readonly",
      "SVGAnimatedPreserveAspectRatio": "readonly",
      "SVGAnimatedRect": "readonly",
      "SVGAnimatedString": "readonly",
      "SVGAnimatedTransformList": "readonly",
      "SVGAnimateElement": "readonly",
      "SVGAnimateMotionElement": "readonly",
      "SVGAnimateTransformElement": "readonly",
      "SVGAnimationElement": "readonly",
      "SVGCircleElement": "readonly",
      "SVGClipPathElement": "readonly",
      "SVGComponentTransferFunctionElement": "readonly",
      "SVGDefsElement": "readonly",
      "SVGDescElement": "readonly",
      "SVGElement": "readonly",
      "SVGEllipseElement": "readonly",
      "SVGFEBlendElement": "readonly",
      "SVGFEColorMatrixElement": "readonly",
      "SVGFEComponentTransferElement": "readonly",
      "SVGFECompositeElement": "readonly",
      "SVGFEConvolveMatrixElement": "readonly",
      "SVGFEDiffuseLightingElement": "readonly",
      "SVGFEDisplacementMapElement": "readonly",
      "SVGFEDistantLightElement": "readonly",
      "SVGFEDropShadowElement": "readonly",
      "SVGFEFloodElement": "readonly",
      "SVGFEFuncAElement": "readonly",
      "SVGFEFuncBElement": "readonly",
      "SVGFEFuncGElement": "readonly",
      "SVGFEFuncRElement": "readonly",
      "SVGFEGaussianBlurElement": "readonly",
      "SVGFEImageElement": "readonly",
      "SVGFEMergeElement": "readonly",
      "SVGFEMergeNodeElement": "readonly",
      "SVGFEMorphologyElement": "readonly",
      "SVGFEOffsetElement": "readonly",
      "SVGFEPointLightElement": "readonly",
      "SVGFESpecularLightingElement": "readonly",
      "SVGFESpotLightElement": "readonly",
      "SVGFETileElement": "readonly",
      "SVGFETurbulenceElement": "readonly",
      "SVGFilterElement": "readonly",
      "SVGForeignObjectElement": "readonly",
      "SVGGElement": "readonly",
      "SVGGeometryElement": "readonly",
      "SVGGradientElement": "readonly",
      "SVGGraphicsElement": "readonly",
      "SVGImageElement": "readonly",
      "SVGLength": "readonly",
      "SVGLengthList": "readonly",
      "SVGLinearGradientElement": "readonly",
      "SVGLineElement": "readonly",
      "SVGMarkerElement": "readonly",
      "SVGMaskElement": "readonly",
      "SVGMatrix": "readonly",
      "SVGMetadataElement": "readonly",
      "SVGMPathElement": "readonly",
      "SVGNumber": "readonly",
      "SVGNumberList": "readonly",
      "SVGPathElement": "readonly",
      "SVGPatternElement": "readonly",
      "SVGPoint": "readonly",
      "SVGPointList": "readonly",
      "SVGPolygonElement": "readonly",
      "SVGPolylineElement": "readonly",
      "SVGPreserveAspectRatio": "readonly",
      "SVGRadialGradientElement": "readonly",
      "SVGRect": "readonly",
      "SVGRectElement": "readonly",
      "SVGScriptElement": "readonly",
      "SVGSetElement": "readonly",
      "SVGStopElement": "readonly",
      "SVGStringList": "readonly",
      "SVGStyleElement": "readonly",
      "SVGSVGElement": "readonly",
      "SVGSwitchElement": "readonly",
      "SVGSymbolElement": "readonly",
      "SVGTextContentElement": "readonly",
      "SVGTextElement": "readonly",
      "SVGTextPathElement": "readonly",
      "SVGTextPositioningElement": "readonly",
      "SVGTitleElement": "readonly",
      "SVGTransform": "readonly",
      "SVGTransformList": "readonly",
      "SVGTSpanElement": "readonly",
      "SVGUnitTypes": "readonly",
      "SVGUseElement": "readonly",
      "SVGViewElement": "readonly",
      "SyncManager": "readonly",
      "TaskAttributionTiming": "readonly",
      "TaskController": "readonly",
      "TaskPriorityChangeEvent": "readonly",
      "TaskSignal": "readonly",
      "TEMPORARY": "readonly",
      "Text": "readonly",
      "TextDecoder": "readonly",
      "TextDecoderStream": "readonly",
      "TextEncoder": "readonly",
      "TextEncoderStream": "readonly",
      "TextEvent": "readonly",
      "TextFormat": "readonly",
      "TextFormatUpdateEvent": "readonly",
      "TextMetrics": "readonly",
      "TextTrack": "readonly",
      "TextTrackCue": "readonly",
      "TextTrackCueList": "readonly",
      "TextTrackList": "readonly",
      "TextUpdateEvent": "readonly",
      "TimeEvent": "readonly",
      "TimeRanges": "readonly",
      "ToggleEvent": "readonly",
      "toolbar": "readonly",
      "top": "readonly",
      "Touch": "readonly",
      "TouchEvent": "readonly",
      "TouchList": "readonly",
      "TrackEvent": "readonly",
      "TransformStream": "readonly",
      "TransformStreamDefaultController": "readonly",
      "TransitionEvent": "readonly",
      "TreeWalker": "readonly",
      "TrustedHTML": "readonly",
      "TrustedScript": "readonly",
      "TrustedScriptURL": "readonly",
      "TrustedTypePolicy": "readonly",
      "TrustedTypePolicyFactory": "readonly",
      "trustedTypes": "readonly",
      "UIEvent": "readonly",
      "URL": "readonly",
      "URLPattern": "readonly",
      "URLSearchParams": "readonly",
      "USB": "readonly",
      "USBAlternateInterface": "readonly",
      "USBConfiguration": "readonly",
      "USBConnectionEvent": "readonly",
      "USBDevice": "readonly",
      "USBEndpoint": "readonly",
      "USBInterface": "readonly",
      "USBInTransferResult": "readonly",
      "USBIsochronousInTransferPacket": "readonly",
      "USBIsochronousInTransferResult": "readonly",
      "USBIsochronousOutTransferPacket": "readonly",
      "USBIsochronousOutTransferResult": "readonly",
      "USBOutTransferResult": "readonly",
      "UserActivation": "readonly",
      "ValidityState": "readonly",
      "VideoColorSpace": "readonly",
      "VideoDecoder": "readonly",
      "VideoEncoder": "readonly",
      "VideoFrame": "readonly",
      "VideoPlaybackQuality": "readonly",
      "ViewTimeline": "readonly",
      "ViewTransition": "readonly",
      "ViewTransitionTypeSet": "readonly",
      "VirtualKeyboard": "readonly",
      "VirtualKeyboardGeometryChangeEvent": "readonly",
      "VisibilityStateEntry": "readonly",
      "visualViewport": "readonly",
      "VisualViewport": "readonly",
      "VTTCue": "readonly",
      "VTTRegion": "readonly",
      "WakeLock": "readonly",
      "WakeLockSentinel": "readonly",
      "WaveShaperNode": "readonly",
      "WebAssembly": "readonly",
      "WebGL2RenderingContext": "readonly",
      "WebGLActiveInfo": "readonly",
      "WebGLBuffer": "readonly",
      "WebGLContextEvent": "readonly",
      "WebGLFramebuffer": "readonly",
      "WebGLObject": "readonly",
      "WebGLProgram": "readonly",
      "WebGLQuery": "readonly",
      "WebGLRenderbuffer": "readonly",
      "WebGLRenderingContext": "readonly",
      "WebGLSampler": "readonly",
      "WebGLShader": "readonly",
      "WebGLShaderPrecisionFormat": "readonly",
      "WebGLSync": "readonly",
      "WebGLTexture": "readonly",
      "WebGLTransformFeedback": "readonly",
      "WebGLUniformLocation": "readonly",
      "WebGLVertexArrayObject": "readonly",
      "WebSocket": "readonly",
      "WebSocketError": "readonly",
      "WebSocketStream": "readonly",
      "WebTransport": "readonly",
      "WebTransportBidirectionalStream": "readonly",
      "WebTransportDatagramDuplexStream": "readonly",
      "WebTransportError": "readonly",
      "WebTransportReceiveStream": "readonly",
      "WebTransportSendStream": "readonly",
      "WGSLLanguageFeatures": "readonly",
      "WheelEvent": "readonly",
      "window": "readonly",
      "Window": "readonly",
      "WindowControlsOverlay": "readonly",
      "WindowControlsOverlayGeometryChangeEvent": "readonly",
      "Worker": "readonly",
      "Worklet": "readonly",
      "WorkletGlobalScope": "readonly",
      "WritableStream": "readonly",
      "WritableStreamDefaultController": "readonly",
      "WritableStreamDefaultWriter": "readonly",
      "XMLDocument": "readonly",
      "XMLHttpRequest": "readonly",
      "XMLHttpRequestEventTarget": "readonly",
      "XMLHttpRequestUpload": "readonly",
      "XMLSerializer": "readonly",
      "XPathEvaluator": "readonly",
      "XPathExpression": "readonly",
      "XPathResult": "readonly",
      "XRAnchor": "readonly",
      "XRAnchorSet": "readonly",
      "XRBoundedReferenceSpace": "readonly",
      "XRCamera": "readonly",
      "XRCPUDepthInformation": "readonly",
      "XRDepthInformation": "readonly",
      "XRDOMOverlayState": "readonly",
      "XRFrame": "readonly",
      "XRHand": "readonly",
      "XRHitTestResult": "readonly",
      "XRHitTestSource": "readonly",
      "XRInputSource": "readonly",
      "XRInputSourceArray": "readonly",
      "XRInputSourceEvent": "readonly",
      "XRInputSourcesChangeEvent": "readonly",
      "XRJointPose": "readonly",
      "XRJointSpace": "readonly",
      "XRLayer": "readonly",
      "XRLightEstimate": "readonly",
      "XRLightProbe": "readonly",
      "XRPose": "readonly",
      "XRRay": "readonly",
      "XRReferenceSpace": "readonly",
      "XRReferenceSpaceEvent": "readonly",
      "XRRenderState": "readonly",
      "XRRigidTransform": "readonly",
      "XRSession": "readonly",
      "XRSessionEvent": "readonly",
      "XRSpace": "readonly",
      "XRSystem": "readonly",
      "XRTransientInputHitTestResult": "readonly",
      "XRTransientInputHitTestSource": "readonly",
      "XRView": "readonly",
      "XRViewerPose": "readonly",
      "XRViewport": "readonly",
      "XRWebGLBinding": "readonly",
      "XRWebGLDepthInformation": "readonly",
      "XRWebGLLayer": "readonly",
      "XSLTProcessor": "readonly",
      "__dirname": "readonly",
      "__filename": "readonly",
      "Buffer": "readonly",
      "clearImmediate": "readonly",
      "process": "readonly",
      "setImmediate": "readonly",
      "__DEV__": "readonly",
      "__PROD__": "readonly",
      "__TEST__": "readonly"
    },
    "ignorePatterns": [
      "**/.docusaurus/",
      "**/build/",
      "**/cjs/",
      "**/coverage/",
      "**/dist/",
      "**/esm/",
      "**/lib/",
      "**/mjs/",
      "**/node_modules/",
      "**/*.d.ts",
      "**/*.json",
      "**/*.snap",
      "**/*.mdx",
      "**/*.css",
      "**/*.html",
      "packages/visualizer/**/*"
    ],
    "rules": {
      "complexity": [
        "error",
        12
      ],
      "prefer-destructuring": [
        "error",
        {
          "object": true,
          "array": false
        }
      ],
      "sort-keys": [
        "error",
        "asc",
        {
          "caseSensitive": false,
          "natural": true
        }
      ],
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-dupe-else-if": "error",
      "no-empty-static-block": "error",
      "no-import-assign": "error",
      "no-new-native-nonconstructor": "error",
      "no-promise-executor-return": "error",
      "no-setter-return": "error",
      "no-unsafe-optional-chaining": [
        "error",
        {
          "disallowArithmeticOperators": true
        }
      ],
      "no-unused-private-class-members": "error",
      "no-useless-call": "error",
      "logical-assignment-operators": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-regex-literals": [
        "error",
        {
          "disallowRedundantWrapping": true
        }
      ],
      "no-implicit-coercion": "error",
      "prefer-object-has-own": "error",
      "default-param-last": "error",
      "no-array-constructor": "error",
      "no-dupe-class-members": "error",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-redeclare": [
        "error",
        {
          "ignoreDeclarationMerge": true
        }
      ],
      "no-shadow": [
        "error",
        {
          "ignoreOnInitialization": true,
          "ignoreTypeValueShadow": true
        }
      ],
      "no-unused-expressions": "error",
      "no-unused-vars": [
        "error",
        {
          "vars": "all",
          "args": "none",
          "caughtErrors": "all",
          "ignoreRestSiblings": true
        }
      ],
      "no-use-before-define": [
        "error",
        {
          "classes": true,
          "enums": true,
          "functions": true,
          "typedefs": true,
          "variables": true
        }
      ],
      "no-useless-constructor": "error",
      "promise/param-names": "error",
      "promise/valid-params": "error",
      "promise/no-promise-in-callback": "error",
      "promise/no-new-statics": "error",
      "promise/catch-or-return": "error",
      "promise/no-return-wrap": [
        "error",
        {
          "allowReject": true
        }
      ],
      "promise/no-multiple-resolved": "error",
      "promise/no-nesting": "error",
      "promise/no-return-in-finally": "error",
      "promise/prefer-await-to-then": "error",
      "promise/prefer-await-to-callbacks": "error",
      "promise/no-callback-in-promise": "off",
      "import/default": "off",
      "import/namespace": "off",
      "import/extensions": [
        "error",
        "ignorePackages",
        {
          "cjs": "always",
          "cts": "always",
          "js": "never",
          "jsx": "never",
          "json": "always",
          "mjs": "always",
          "mts": "always",
          "ts": "never",
          "tsx": "never"
        }
      ],
      "import/no-amd": "error",
      "import/no-commonjs": [
        "error",
        {
          "allowRequire": true,
          "allowConditionalRequire": true
        }
      ],
      "import/no-default-export": "error",
      "unicorn/escape-case": "error",
      "unicorn/no-console-spaces": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-hex-escape": "error",
      "unicorn/no-negated-condition": "error",
      "unicorn/no-typeof-undefined": "error",
      "unicorn/no-unreadable-iife": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-native-coercion-functions": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-structured-clone": "error",
      "unicorn/relative-url-style": [
        "error",
        "always"
      ],
      "unicorn/text-encoding-identifier-case": "error",
      "unicorn/catch-error-name": "error",
      "unicorn/custom-error-definition": "error",
      "unicorn/error-message": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-anonymous-default-export": "error",
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-negation-in-equality-check": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-this-assignment": "error",
      "unicorn/no-useless-spread": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/numeric-separators-style": "error",
      "unicorn/switch-case-braces": [
        "error",
        "avoid"
      ],
      "unicorn/throw-new-error": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/no-abusive-eslint-disable": "error",
      "unicorn/no-array-method-this-argument": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/prefer-negative-index": "error",
      "unicorn/prefer-prototype-methods": "error",
      "unicorn/require-array-join-separator": "error",
      "unicorn/require-number-to-fixed-digits-argument": "error",
      "unicorn/require-post-message-target-origin": "error",
      "unicorn/no-lonely-if": "error",
      "unicorn/no-static-only-class": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-ternary": "error",
      "unicorn/prefer-default-parameters": "error",
      "unicorn/no-object-as-default-parameter": "error",
      "unicorn/no-unreadable-array-destructuring": "error",
      "unicorn/no-process-exit": "error",
      "unicorn/no-document-cookie": "error",
      "unicorn/prefer-add-event-listener": "error",
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-array-flat": "error",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-index-of": "error",
      "unicorn/prefer-array-some": "error",
      "unicorn/prefer-code-point": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-dataset": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-includes": "error",
      "unicorn/prefer-keyboard-event-key": "error",
      "unicorn/prefer-math-trunc": "error",
      "unicorn/prefer-modern-dom-apis": "error",
      "unicorn/prefer-modern-math-apis": "error",
      "unicorn/prefer-module": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-spread": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-top-level-await": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-string-replace-all": "error",
      "typescript/no-implied-eval": "error",
      "typescript/only-throw-error": "error",
      "typescript/require-await": "error",
      "typescript/return-await": [
        "error",
        "in-try-catch"
      ],
      "typescript/adjacent-overload-signatures": "error",
      "typescript/array-type": [
        "error",
        {
          "default": "array"
        }
      ],
      "typescript/consistent-indexed-object-style": [
        "error",
        "record"
      ],
      "typescript/no-inferrable-types": [
        "error",
        {
          "ignoreParameters": true,
          "ignoreProperties": true
        }
      ],
      "typescript/prefer-function-type": "error",
      "typescript/no-unnecessary-boolean-literal-compare": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/consistent-type-definitions": [
        "error",
        "interface"
      ],
      "typescript/no-empty-interface": [
        "error",
        {
          "allowSingleExtends": true
        }
      ],
      "typescript/no-explicit-any": [
        "error",
        {
          "ignoreRestArgs": true
        }
      ],
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/await-thenable": "off",
      "typescript/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": "allow-with-description",
          "ts-ignore": true,
          "ts-nocheck": true,
          "ts-check": false,
          "minimumDescriptionLength": 3
        }
      ],
      "typescript/ban-tslint-comment": "error",
      "typescript/prefer-ts-expect-error": "error",
      "typescript/triple-slash-reference": [
        "error",
        {
          "path": "never",
          "types": "never",
          "lib": "never"
        }
      ],
      "typescript/require-array-sort-compare": "off",
      "typescript/restrict-template-expressions": "off",
      "typescript/unbound-method": [
        "off",
        {
          "ignoreStatic": true
        }
      ],
      "typescript/consistent-type-assertions": [
        "error",
        {
          "assertionStyle": "as",
          "objectLiteralTypeAssertions": "allow-as-parameter"
        }
      ],
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-non-null-asserted-nullish-coalescing": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/non-nullable-type-assertion-style": "error",
      "typescript/prefer-as-const": "error",
      "typescript/explicit-member-accessibility": [
        "error",
        {
          "accessibility": "no-public"
        }
      ],
      "typescript/parameter-properties": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-confusing-void-expression": [
        "error",
        {
          "ignoreVoidOperator": true
        }
      ],
      "typescript/no-floating-promises": [
        "error",
        {
          "ignoreIIFE": true,
          "ignoreVoid": true
        }
      ],
      "typescript/no-misused-promises": [
        "error",
        {
          "checksConditionals": true
        }
      ],
      "typescript/promise-function-async": [
        "error",
        {
          "allowedPromiseNames": [
            "Awaitable",
            "PromiseLike",
            "Thenable"
          ],
          "allowAny": true,
          "checkArrowFunctions": false
        }
      ],
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/no-extraneous-class": "error",
      "typescript/no-namespace": [
        "error",
        {
          "allowDeclarations": true,
          "allowDefinitionFiles": true
        }
      ],
      "typescript/no-array-delete": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-for-in-array": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-this-alias": [
        "error",
        {
          "allowDestructuring": true
        }
      ],
      "typescript/no-unnecessary-qualifier": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/prefer-for-of": "error",
      "typescript/prefer-literal-enum-member": "error",
      "typescript/prefer-reduce-type-parameter": "error",
      "typescript/restrict-plus-operands": [
        "error",
        {
          "skipCompoundAssignments": true
        }
      ],
      "typescript/unified-signatures": [
        "error",
        {
          "ignoreDifferentlyNamedParameters": true
        }
      ],
      "typescript/no-useless-empty-export": "off",
      "typescript/prefer-includes": "error",
      "typescript/prefer-namespace-keyword": "off",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-optional-chain": "error",
      "typescript/prefer-string-starts-ends-with": "error",
      "typescript/switch-exhaustiveness-check": "error",
      "vite-plus/prefer-vite-plus-imports": "error"
    },
    "overrides": [
      {
        "files": [
          "**/index.*"
        ],
        "rules": {
          "import/no-default-export": "off"
        }
      },
      {
        "files": [
          "**/.*.{ts,tsx,cts,mts,js,jsx,cjs,mjs}",
          "**/*.config.{ts,tsx,cts,mts,js,jsx,cjs,mjs}"
        ],
        "rules": {
          "import/no-commonjs": "off",
          "unicorn/prefer-module": "off"
        }
      },
      {
        "files": [
          "**/{tests,__tests__}/**/*.test.{ts,tsx,cts,mts,js,jsx,cjs,mjs}",
          "**/{tests,__tests__}/**/*.{ts,tsx,cts,mts,js,jsx,cjs,mjs}",
          "**/test.{ts,tsx,cts,mts,js,jsx,cjs,mjs}"
        ],
        "rules": {
          "max-classes-per-file": "off",
          "no-console": "off",
          "sort-keys": "off",
          "promise/prefer-await-to-callbacks": "off",
          "no-useless-constructor": "off",
          "typescript/no-extraneous-class": "off",
          "typescript/promise-function-async": "off",
          "typescript/no-explicit-any": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off"
        },
        "globals": {
          "__dirname": "readonly",
          "__filename": "readonly",
          "AbortController": "readonly",
          "AbortSignal": "readonly",
          "atob": "readonly",
          "Blob": "readonly",
          "BroadcastChannel": "readonly",
          "btoa": "readonly",
          "Buffer": "readonly",
          "ByteLengthQueuingStrategy": "readonly",
          "clearImmediate": "readonly",
          "clearInterval": "readonly",
          "clearTimeout": "readonly",
          "CloseEvent": "readonly",
          "CompressionStream": "readonly",
          "console": "readonly",
          "CountQueuingStrategy": "readonly",
          "crypto": "readonly",
          "Crypto": "readonly",
          "CryptoKey": "readonly",
          "CustomEvent": "readonly",
          "DecompressionStream": "readonly",
          "DOMException": "readonly",
          "Event": "readonly",
          "EventTarget": "readonly",
          "fetch": "readonly",
          "File": "readonly",
          "FormData": "readonly",
          "Headers": "readonly",
          "MessageChannel": "readonly",
          "MessageEvent": "readonly",
          "MessagePort": "readonly",
          "navigator": "readonly",
          "Navigator": "readonly",
          "performance": "readonly",
          "Performance": "readonly",
          "PerformanceEntry": "readonly",
          "PerformanceMark": "readonly",
          "PerformanceMeasure": "readonly",
          "PerformanceObserver": "readonly",
          "PerformanceObserverEntryList": "readonly",
          "PerformanceResourceTiming": "readonly",
          "process": "readonly",
          "queueMicrotask": "readonly",
          "ReadableByteStreamController": "readonly",
          "ReadableStream": "readonly",
          "ReadableStreamBYOBReader": "readonly",
          "ReadableStreamBYOBRequest": "readonly",
          "ReadableStreamDefaultController": "readonly",
          "ReadableStreamDefaultReader": "readonly",
          "Request": "readonly",
          "Response": "readonly",
          "setImmediate": "readonly",
          "setInterval": "readonly",
          "setTimeout": "readonly",
          "structuredClone": "readonly",
          "SubtleCrypto": "readonly",
          "TextDecoder": "readonly",
          "TextDecoderStream": "readonly",
          "TextEncoder": "readonly",
          "TextEncoderStream": "readonly",
          "TransformStream": "readonly",
          "TransformStreamDefaultController": "readonly",
          "URL": "readonly",
          "URLSearchParams": "readonly",
          "WebAssembly": "readonly",
          "WebSocket": "readonly",
          "WritableStream": "readonly",
          "WritableStreamDefaultController": "readonly",
          "WritableStreamDefaultWriter": "readonly"
        },
        "env": {
          "jest": true,
          "vitest": true
        }
      },
      {
        "files": [
          "**/{__mocks__,__fixtures__}/**/*",
          "**/{tests,__tests__}/**/{helpers,utils,setup}.{ts,tsx,cts,mts,js,jsx,cjs,mjs}"
        ],
        "rules": {
          "import/no-commonjs": "off",
          "typescript/no-explicit-any": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off"
        }
      },
      {
        "files": [
          "packages/types/**/*"
        ],
        "rules": {
          "unicorn/no-abusive-eslint-disable": "off"
        }
      },
      {
        "files": [
          "scripts/**/*"
        ],
        "rules": {
          "no-console": "off",
          "promise/prefer-await-to-callbacks": "off",
          "unicorn/no-process-exit": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off"
        }
      },
      {
        "files": [
          "website/**/*"
        ],
        "rules": {
          "import/no-default-export": "off"
        }
      }
    ]
  },
  fmt: {
    arrowParens: "always",
    bracketSameLine: false,
    bracketSpacing: true,
    embeddedLanguageFormatting: "auto",
    endOfLine: "lf",
    printWidth: 100,
    proseWrap: "always",
    semi: true,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: true,
    sortPackageJson: false,
    ignorePatterns: [
      "coverage/",
      ".docusaurus/",
      "coverage/",
      "build/",
      "cjs/",
      "dts/",
      "esm/",
      "lib/",
      "mjs/",
      "node_modules/",
      "umd/",
      "dist/",
      "*.json",
      "crates/config/templates/",
      "packages/visualizer/*timestamp*",
    ],
  },
});
