[package]
name = "moon_javascript_platform"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_args = { path = "../../../crates/args" }
moon_common = { path = "../../../crates/common" }
moon_config = { path = "../../../crates/config" }
moon_node_lang = { path = "../../node/lang" }
moon_project = { path = "../../../crates/project" }
moon_target = { path = "../../../crates/target" }
moon_toolchain = { path = "../../../crates/toolchain" }
moon_utils = { path = "../../core/utils" }
miette = { workspace = true }
rustc-hash = { workspace = true }
starbase_styles = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
