[package]
name = "moon_task_hasher"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Task content hashing."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_env_var = { path = "../env-var" }
moon_feature_flags = { path = "../feature-flags" }
moon_hash = { path = "../hash" }
moon_project = { path = "../project" }
moon_task = { path = "../task" }
moon_vcs = { path = "../vcs" }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["glob"] }
tracing = { workspace = true }

[dev-dependencies]
moon_test_utils2 = { path = "../test-utils" }
starbase_sandbox = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
