[package]
name = "moon_token"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Token resolving."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_env_var = { path = "../env-var" }
moon_file_group = { path = "../file-group" }
moon_graph_utils = { path = "../graph-utils" }
moon_project = { path = "../project" }
moon_project_graph = { path = "../project-graph" }
moon_task = {  path = "../task" }
moon_time = { path = "../time" }
convert_case = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tera = { version = "2.1.0", features = ["fast"] }

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
