[package]
name = "moon_python_tool"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_python_lang = { path = "../lang" }
moon_common = { path = "../../../crates/common" }
moon_config = { path = "../../../crates/config" }
moon_console = { path = "../../../crates/console" }
moon_logger = { path = "../../core/logger" }
moon_process = { path = "../../../crates/process" }
moon_tool = { path = "../../core/tool" }
moon_utils = { path = "../../core/utils" }
moon_toolchain = { path = "../../../crates/toolchain" }
starbase_styles = { workspace = true }
miette = { workspace = true }
proto_core = { workspace = true }
rustc-hash = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
