[package]
name = "tc_tier2"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
tc_tier1 = { path = "../tc-tier1" }
moon_common = { workspace = true }
moon_config = { workspace = true }
moon_pdk = { workspace = true }
moon_pdk_api = { workspace = true }
moon_target = { workspace = true }
extism-pdk = { workspace = true }
