[package]
name = "moon_file_group"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "File groups and collections."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "0.1.0", path = "../common" }
moon_config = { version = "0.1.2", path = "../config" }
moon_feature_flags = { version = "0.0.1", path = "../feature-flags" }
common-path = "1.0.0"
miette = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["glob"] }
thiserror = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
