[package]
name = "moon_notifier"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_time = { path = "../time" }
ci_env = { workspace = true }
miette = { workspace = true }
notify-rust = { version = "4.11.7", default-features = false, features = ["z"] }
reqwest = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
system_env = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
