[package]
name = "moon_vcs_hooks"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "VCS hooks management."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_hash = { path = "../hash" }
moon_vcs = { path = "../vcs" }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true }
system_env = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
