// These types can't be generated by schematic currently.

export type TaskCommandArgs = string[] | string | null;

export type TaskOptionAffectedFiles = boolean | 'args' | 'env';

export type TaskOptionEnvFile = boolean | string;

export type OwnersPaths = Record<string, string> | string[];

export type ProjectDependsOn = string | { id: string; scope: string };

export type WorkspaceProjects =
	| Record<string, string>
	| string[]
	| {
			globs: string[];
			sources: Record<string, string>;
	  };
