// These types can't be generated by schematic currently.

export type OwnersPaths = Record<string, string> | string[];

export type ProjectDependsOn = string | { id: string; scope: string };

export type WorkspaceProjects =
	| Record<string, string>
	| string[]
	| {
			globs: string[];
			sources: Record<string, string>;
	  };
