// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

export type Id = string;

export type Target = string;

export type FilePath = string;

export type GlobPath = string;

export type InputPath = string;

export type OutputPath = string;

export type LanguageType = 'bash' | 'batch' | 'go' | 'javascript' | 'php' | 'python' | 'ruby' | 'rust' | 'typescript' | 'unknown' | '';

export type PlatformType = 'deno' | 'node' | 'rust' | 'system' | 'unknown';