// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

import type { ExtendsFrom, Id } from './common';
import type { PluginLocator } from './toolchains-config';

/** Configures an individual extension. */
export interface ExtensionPluginConfig {
	/** Arbitrary configuration that'll be passed to the WASM plugin. */
	config: Record<string, unknown>;
	/** Location of the WASM plugin to use. */
	plugin: PluginLocator | null;
}

/** Configures all extensions. */
export interface ExtensionsConfig {
	/** @default './cache/schemas/extensions.json' */
	$schema?: string;
	/**
	 * Extends one or many extensions configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 2.0.0
	 */
	extends: ExtendsFrom | null;
	/**
	 * Configures and integrates extensions into the system using
	 * a unique identifier.
	 */
	plugins: Record<Id, ExtensionPluginConfig>;
}
