// Automatically generated by schematic. DO NOT MODIFY!

 

import type { ExtendsFrom, Id } from './common';
import type { PluginLocator } from './toolchains-config';

export type ExtensionPluginConfigConfig = Record<string, unknown>;

/** Configures an individual extension. */
export interface ExtensionPluginConfigBase {
	/** Location of the WASM plugin to use. */
	plugin?: PluginLocator | null;
}

/** Configures an individual extension. */
export type ExtensionPluginConfig = ExtensionPluginConfigBase & ExtensionPluginConfigConfig;

export type ExtensionsConfigPlugins = Record<Id, ExtensionPluginConfig>;

/** Configures all extensions. */
export interface ExtensionsConfigBase {
	/** @default './cache/schemas/extensions.json' */
	$schema?: string;
	/**
	 * Extends one or many extensions configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 2.0.0
	 */
	extends?: ExtendsFrom | null;
}

/** Configures all extensions. */
export type ExtensionsConfig = ExtensionsConfigBase & ExtensionsConfigPlugins;
