// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

import type { Id } from './common';
import type { Input, PartialTaskConfig, TaskConfig } from './tasks-config';
import type { PartialToolchainPluginConfig, ToolchainPluginConfig } from './toolchains-config';

/** The relationship scope of a dependency. */
export type DependencyScope = 'build' | 'development' | 'peer' | 'production' | 'root';

/**
 * The source where the dependency comes from. Either explicitly
 * defined in configuration, or implicitly derived from source files.
 */
export type DependencySource = 'explicit' | 'implicit';

/** Expanded information about a project dependency. */
export interface ProjectDependencyConfig {
	/** Identifier of the depended on project. */
	id: Id;
	/**
	 * Scope of the dependency relationship.
	 *
	 * @default 'production'
	 * @type {'build' | 'development' | 'peer' | 'production' | 'root'}
	 */
	scope: DependencyScope;
	/**
	 * Source of where the dependency came from.
	 *
	 * @default 'explicit'
	 * @type {'explicit' | 'implicit'}
	 */
	source: DependencySource;
	/** Metadata about the source. */
	via: string | null;
}

export type ProjectDependsOn = Id | ProjectDependencyConfig;

/**
 * Configures `Dockerfile` generation.
 * @since 1.27.0
 */
export interface ProjectDockerFileConfig {
	/** A task identifier within the current project for building the project. */
	buildTask: Id | null;
	/** The base Docker image name. */
	image: string | null;
	/** A task identifier within the current project for starting the project. */
	startTask: Id | null;
}

/**
 * Configures aspects of the Docker scaffolding process.
 * @since 1.27.0
 */
export interface ProjectDockerScaffoldConfig {
	/**
	 * A list of glob patterns, relative from the project root,
	 * to include (or exclude) in the sources skeleton.
	 */
	include: string[];
}

/**
 * Configures our Docker integration.
 * @since 1.27.0
 */
export interface ProjectDockerConfig {
	/** Configures aspects of the `Dockerfile` generation process. */
	file: ProjectDockerFileConfig;
	/** Configures aspects of the Docker scaffolding process. */
	scaffold: ProjectDockerScaffoldConfig;
}

/** Supported programming languages that each project can be written in. */
export type LanguageType =
	| 'bash'
	| 'batch'
	| 'cplusplus'
	| 'csharp'
	| 'dotnet'
	| 'go'
	| 'java'
	| 'javascript'
	| 'kotlin'
	| 'php'
	| 'python'
	| 'ruby'
	| 'rust'
	| 'swift'
	| 'typescript'
	| 'unknown'
	| string;

/** The layer within the technology stack, for categorizing. */
export type LayerType =
	| 'application'
	| 'automation'
	| 'configuration'
	| 'library'
	| 'scaffolding'
	| 'tool'
	| 'unknown';

export type OwnersPaths = string[] | Record<string, string[]>;

/**
 * Defines ownership of source code within the current project, by mapping
 * file paths and glob patterns to owners. An owner is either a user, team, or group.
 */
export interface OwnersConfig {
	/**
	 * Bitbucket only. A map of custom groups (prefixed with `@@@`),
	 * to a list of user and normal groups.
	 */
	customGroups: Record<string, string[]>;
	/** The default owner for `paths`. */
	defaultOwner: string | null;
	/** GitLab only. Marks the code owners section as optional. */
	optional: boolean;
	/**
	 * A list or map of file paths and glob patterns to owners.
	 * When a list, the `defaultOwner` is the owner, and each item is a path.
	 * When a map, the key is a path, and the value is a list of owners.
	 */
	paths: OwnersPaths;
	/**
	 * Bitbucket and GitLab only. The number of approvals required for the
	 * request to be satisfied. For Bitbucket, utilizes the `Check()` condition.
	 * For GitLab, marks the code owners section as required.
	 */
	requiredApprovals: number | null;
}

/** Expanded information about the project. */
export interface ProjectMetadataConfig {
	/**
	 * The Slack, Discord, IRC, etc, channel to discuss the project.
	 * Must start with a `#`.
	 */
	channel: string | null;
	/** A description on what the project does and why it exists. */
	description: string | null;
	/** The individual maintainers of the project. The format is unspecified. */
	maintainers: string[];
	/** Custom metadata fields. */
	metadata: Record<string, unknown>;
	/**
	 * The owner of the project. Can be an individual, team, or
	 * organization. The format is unspecified.
	 */
	owner: string | null;
	/** A human-readable title of the project. */
	title: string | null;
}

/** The technology stack of the project, for categorizing. */
export type StackType = 'backend' | 'frontend' | 'infrastructure' | 'systems' | 'unknown';

export type ProjectToolchainEntry = null | boolean | ToolchainPluginConfig;

/** Overrides top-level toolchain settings, scoped to this project. */
export interface ProjectToolchainsConfig {
	/**
	 * A single toolchain, or list of toolchains, to inherit for
	 * this project and all of its tasks.
	 * @since 1.31.0
	 */
	defaults?: Id | Id[] | null;
	/**
	 * A single toolchain, or list of toolchains, to inherit for
	 * this project and all of its tasks.
	 * @since 1.31.0
	 */
	default: Id | Id[] | null;
	/** Overrides workspace-level toolchains by their identifier. */
	plugins: Record<Id, ProjectToolchainEntry>;
}

/** Controls how workspace-level tasks are inherited. */
export interface ProjectWorkspaceInheritedTasksConfig {
	/** Excludes inheriting tasks by their identifier. */
	exclude: Id[];
	/**
	 * Only inherits tasks with the provided identifiers,
	 * and ignores the rest. When not defined, inherits
	 * all matching tasks. When an empty list, inherits no tasks.
	 */
	include: Id[] | null;
	/**
	 * Renames inherited tasks by mapping their existing
	 * identifier to a new identifier, scoped to this project.
	 */
	rename: Record<Id, Id>;
}

/** Overrides workspace settings, scoped to this project. */
export interface ProjectWorkspaceConfig {
	/** Controls how tasks are inherited. */
	inheritedTasks: ProjectWorkspaceInheritedTasksConfig;
}

/**
 * Configures information and tasks for a project.
 * Docs: https://moonrepo.dev/docs/config/project
 */
export interface ProjectConfig {
	/** @default 'https://moonrepo.dev/schemas/project.json' */
	$schema?: string;
	/** Other projects that this project depends on. */
	deps?: ProjectDependsOn[];
	/** Other projects that this project depends on. */
	dependsOn: ProjectDependsOn[];
	/**
	 * Configures Docker integration for this project.
	 * @since 1.27.0
	 */
	docker: ProjectDockerConfig;
	/**
	 * A map of environment variables that will be inherited by
	 * all tasks within the project.
	 */
	env: Record<string, string>;
	/**
	 * A map of group identifiers to a list of file paths, globs, and
	 * environment variables, that can be referenced from tasks.
	 */
	fileGroups: Record<Id, Input[]>;
	/**
	 * Overrides the identifier within the project graph, as defined in
	 * the workspace `projects` setting.
	 * @since 1.18.0
	 */
	id: Id | null;
	/**
	 * The primary programming language of the project.
	 *
	 * @default 'unknown'
	 * @type {'bash' | 'batch' | 'cplusplus' | 'csharp' | 'dotnet' | 'go' | 'java' | 'javascript' | 'kotlin' | 'php' | 'python' | 'ruby' | 'rust' | 'swift' | 'typescript' | 'unknown' | string}
	 */
	language: LanguageType;
	/**
	 * The layer within the technology stack, for categorizing.
	 *
	 * @default 'unknown'
	 * @type {'application' | 'automation' | 'configuration' | 'library' | 'scaffolding' | 'tool' | 'unknown'}
	 */
	layer: LayerType;
	/**
	 * Defines ownership of source code within the current project, by mapping
	 * file paths and globs to owners. An owner is either a user, team, or group.
	 * @since 1.8.0
	 */
	owners: OwnersConfig;
	/** Expanded information about the project. */
	project: ProjectMetadataConfig | null;
	/**
	 * The technology stack of the project, for categorizing.
	 * @since 1.22.0
	 *
	 * @default 'unknown'
	 * @type {'backend' | 'frontend' | 'infrastructure' | 'systems' | 'unknown'}
	 */
	stack: StackType;
	/**
	 * A list of tags that this project belongs to, for categorizing,
	 * boundary enforcement, and task inheritance.
	 */
	tags: Id[];
	/**
	 * A map of identifiers to task objects. Tasks represent the work-unit
	 * of a project, and can be ran in the action pipeline.
	 */
	tasks: Record<Id, TaskConfig>;
	/** Overrides top-level toolchain settings, scoped to this project. */
	toolchains: ProjectToolchainsConfig;
	/** Overrides top-level workspace settings, scoped to this project. */
	workspace: ProjectWorkspaceConfig;
}

/** Expanded information about a project dependency. */
export interface PartialProjectDependencyConfig {
	/** Identifier of the depended on project. */
	id?: Id | null;
	/**
	 * Scope of the dependency relationship.
	 *
	 * @default 'production'
	 */
	scope?: DependencyScope | null;
	/**
	 * Source of where the dependency came from.
	 *
	 * @default 'explicit'
	 */
	source?: DependencySource | null;
	/** Metadata about the source. */
	via?: string | null;
}

export type PartialProjectDependsOn = Id | PartialProjectDependencyConfig;

/**
 * Configures `Dockerfile` generation.
 * @since 1.27.0
 */
export interface PartialProjectDockerFileConfig {
	/** A task identifier within the current project for building the project. */
	buildTask?: Id | null;
	/** The base Docker image name. */
	image?: string | null;
	/** A task identifier within the current project for starting the project. */
	startTask?: Id | null;
}

/**
 * Configures aspects of the Docker scaffolding process.
 * @since 1.27.0
 */
export interface PartialProjectDockerScaffoldConfig {
	/**
	 * A list of glob patterns, relative from the project root,
	 * to include (or exclude) in the sources skeleton.
	 */
	include?: string[] | null;
}

/**
 * Configures our Docker integration.
 * @since 1.27.0
 */
export interface PartialProjectDockerConfig {
	/** Configures aspects of the `Dockerfile` generation process. */
	file?: PartialProjectDockerFileConfig | null;
	/** Configures aspects of the Docker scaffolding process. */
	scaffold?: PartialProjectDockerScaffoldConfig | null;
}

export type PartialOwnersPaths = string[] | Record<string, string[]>;

/**
 * Defines ownership of source code within the current project, by mapping
 * file paths and glob patterns to owners. An owner is either a user, team, or group.
 */
export interface PartialOwnersConfig {
	/**
	 * Bitbucket only. A map of custom groups (prefixed with `@@@`),
	 * to a list of user and normal groups.
	 */
	customGroups?: Record<string, string[]> | null;
	/** The default owner for `paths`. */
	defaultOwner?: string | null;
	/** GitLab only. Marks the code owners section as optional. */
	optional?: boolean | null;
	/**
	 * A list or map of file paths and glob patterns to owners.
	 * When a list, the `defaultOwner` is the owner, and each item is a path.
	 * When a map, the key is a path, and the value is a list of owners.
	 */
	paths?: PartialOwnersPaths | null;
	/**
	 * Bitbucket and GitLab only. The number of approvals required for the
	 * request to be satisfied. For Bitbucket, utilizes the `Check()` condition.
	 * For GitLab, marks the code owners section as required.
	 */
	requiredApprovals?: number | null;
}

/** Expanded information about the project. */
export interface PartialProjectMetadataConfig {
	/**
	 * The Slack, Discord, IRC, etc, channel to discuss the project.
	 * Must start with a `#`.
	 */
	channel?: string | null;
	/** A description on what the project does and why it exists. */
	description?: string | null;
	/** The individual maintainers of the project. The format is unspecified. */
	maintainers?: string[] | null;
	/** Custom metadata fields. */
	metadata?: Record<string, unknown> | null;
	/**
	 * The owner of the project. Can be an individual, team, or
	 * organization. The format is unspecified.
	 */
	owner?: string | null;
	/** A human-readable title of the project. */
	title?: string | null;
}

export type PartialProjectToolchainEntry = null | boolean | PartialToolchainPluginConfig;

/** Overrides top-level toolchain settings, scoped to this project. */
export interface PartialProjectToolchainsConfig {
	/**
	 * A single toolchain, or list of toolchains, to inherit for
	 * this project and all of its tasks.
	 * @since 1.31.0
	 */
	defaults?: Id | Id[] | null;
	/**
	 * A single toolchain, or list of toolchains, to inherit for
	 * this project and all of its tasks.
	 * @since 1.31.0
	 */
	default?: Id | Id[] | null;
	/** Overrides workspace-level toolchains by their identifier. */
	plugins?: Record<Id, PartialProjectToolchainEntry> | null;
}

/** Controls how workspace-level tasks are inherited. */
export interface PartialProjectWorkspaceInheritedTasksConfig {
	/** Excludes inheriting tasks by their identifier. */
	exclude?: Id[] | null;
	/**
	 * Only inherits tasks with the provided identifiers,
	 * and ignores the rest. When not defined, inherits
	 * all matching tasks. When an empty list, inherits no tasks.
	 */
	include?: Id[] | null;
	/**
	 * Renames inherited tasks by mapping their existing
	 * identifier to a new identifier, scoped to this project.
	 */
	rename?: Record<Id, Id> | null;
}

/** Overrides workspace settings, scoped to this project. */
export interface PartialProjectWorkspaceConfig {
	/** Controls how tasks are inherited. */
	inheritedTasks?: PartialProjectWorkspaceInheritedTasksConfig | null;
}

/**
 * Configures information and tasks for a project.
 * Docs: https://moonrepo.dev/docs/config/project
 */
export interface PartialProjectConfig {
	/** @default 'https://moonrepo.dev/schemas/project.json' */
	$schema?: string | null;
	/** Other projects that this project depends on. */
	deps?: PartialProjectDependsOn[] | null;
	/** Other projects that this project depends on. */
	dependsOn?: PartialProjectDependsOn[] | null;
	/**
	 * Configures Docker integration for this project.
	 * @since 1.27.0
	 */
	docker?: PartialProjectDockerConfig | null;
	/**
	 * A map of environment variables that will be inherited by
	 * all tasks within the project.
	 */
	env?: Record<string, string> | null;
	/**
	 * A map of group identifiers to a list of file paths, globs, and
	 * environment variables, that can be referenced from tasks.
	 */
	fileGroups?: Record<Id, Input[]> | null;
	/**
	 * Overrides the identifier within the project graph, as defined in
	 * the workspace `projects` setting.
	 * @since 1.18.0
	 */
	id?: Id | null;
	/**
	 * The primary programming language of the project.
	 *
	 * @default 'unknown'
	 */
	language?: LanguageType | null;
	/**
	 * The layer within the technology stack, for categorizing.
	 *
	 * @default 'unknown'
	 */
	layer?: LayerType | null;
	/**
	 * Defines ownership of source code within the current project, by mapping
	 * file paths and globs to owners. An owner is either a user, team, or group.
	 * @since 1.8.0
	 */
	owners?: PartialOwnersConfig | null;
	/** Expanded information about the project. */
	project?: PartialProjectMetadataConfig | null;
	/**
	 * The technology stack of the project, for categorizing.
	 * @since 1.22.0
	 *
	 * @default 'unknown'
	 */
	stack?: StackType | null;
	/**
	 * A list of tags that this project belongs to, for categorizing,
	 * boundary enforcement, and task inheritance.
	 */
	tags?: Id[] | null;
	/**
	 * A map of identifiers to task objects. Tasks represent the work-unit
	 * of a project, and can be ran in the action pipeline.
	 */
	tasks?: Record<Id, PartialTaskConfig> | null;
	/** Overrides top-level toolchain settings, scoped to this project. */
	toolchains?: PartialProjectToolchainsConfig | null;
	/** Overrides top-level workspace settings, scoped to this project. */
	workspace?: PartialProjectWorkspaceConfig | null;
}
