// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

import type { ExtendsFrom, Id } from './common';
import type { LanguageType, LayerType, StackType } from './project-config';

/** The task-to-task relationship of the dependency. */
export type TaskDependencyType = 'cleanup' | 'required' | 'optional';

/** A file path input. */
export interface FileInput {
	/**
	 * Regex pattern to match the file's contents against
	 * when determining affected status.
	 */
	content: string | null;
	/** The literal file path. */
	file: string;
	/**
	 * Mark the file as optional instead of logging a warning
	 * when hashing a task.
	 */
	optional?: boolean | null;
}

/** Available formats to resolve the file group into. */
export type FileGroupInputFormat = 'static' | 'dirs' | 'envs' | 'files' | 'globs' | 'root';

/** A file group input. */
export interface FileGroupInput {
	/**
	 * Format to resolve the file group into.
	 *
	 * @default 'static'
	 * @type {'static' | 'dirs' | 'envs' | 'files' | 'globs' | 'root'}
	 */
	as?: FileGroupInputFormat;
	/**
	 * Format to resolve the file group into.
	 *
	 * @default 'static'
	 * @type {'static' | 'dirs' | 'envs' | 'files' | 'globs' | 'root'}
	 */
	format?: FileGroupInputFormat;
	/** The file group identifier. */
	group: Id;
}

/** A glob pattern input. */
export interface GlobInput {
	/**
	 * Cache the glob walking result for increased performance.
	 *
	 * @default true
	 */
	cache?: boolean;
	/** The glob pattern. */
	glob: string;
}

/** An external project input. */
export interface ProjectInput {
	/**
	 * A list of globs, relative from the project's root,
	 * in which to determine affected status.
	 */
	filter?: string[];
	/**
	 * A file group identifier within the project in which
	 * to determine affected status.
	 */
	fileGroup?: Id | null;
	/**
	 * A file group identifier within the project in which
	 * to determine affected status.
	 */
	group?: Id | null;
	/** The external project identifier. */
	project: string;
}

export type Input = string | FileInput | FileGroupInput | GlobInput | ProjectInput;

export type TaskArgs = null | string | string[];

/** Expanded information about a task dependency. */
export interface TaskDependencyConfig {
	/** Additional arguments to pass to this dependency when it's ran. */
	args: TaskArgs;
	/** A map of environment variables specific to this dependency. */
	env: Record<string, string | null>;
	/**
	 * Marks the dependency as optional when being inherited from the top-level.
	 * @since 1.20.0
	 */
	optional: boolean | null;
	/** The target of the depended on task. */
	target: string;
}

export type TaskDependency = string | TaskDependencyConfig;

/**
 * A condition that utilizes a combination of logical operators
 * to match against. When matching, all clauses must be satisfied.
 */
export interface InheritedClauseConfig {
	/** Require all values to match, using an AND operator. */
	and: Id | Id[] | null;
	/** Require no values to match, using a NOT operator. */
	not: Id | Id[] | null;
	/** Require any values to match, using an OR operator. */
	or: Id | Id[] | null;
}

export type InheritedConditionConfig = Id | Id[] | InheritedClauseConfig;

/**
 * Configures conditions that must match against a project for tasks
 * to be inherited. If multiple conditions are defined, then all must match
 * for inheritance to occur. If no conditions are defined, then tasks will
 * be inherited by all projects.
 */
export interface InheritedByConfig {
	/**
	 * Condition that matches against literal files within a project.
	 * If multiple values are provided, at least 1 file needs to exist.
	 */
	file?: string | string[] | null;
	/**
	 * Condition that matches against literal files within a project.
	 * If multiple values are provided, at least 1 file needs to exist.
	 */
	files: string | string[] | null;
	/**
	 * Condition that matches against a project's `language`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	language?: LanguageType | LanguageType[] | null;
	/**
	 * Condition that matches against a project's `language`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	languages: LanguageType | LanguageType[] | null;
	/**
	 * Condition that matches against a project's `layer`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	layer?: LayerType | LayerType[] | null;
	/**
	 * Condition that matches against a project's `layer`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	layers: LayerType | LayerType[] | null;
	/**
	 * The order in which this configuration is inherited by a project.
	 * Lower is inherited first, while higher is last.
	 */
	order: number | null;
	/**
	 * Condition that matches against a project's `stack`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	stack?: StackType | StackType[] | null;
	/**
	 * Condition that matches against a project's `stack`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	stacks: StackType | StackType[] | null;
	/** Condition that matches against a tag within the project. */
	tag?: InheritedConditionConfig | null;
	/** Condition that matches against a tag within the project. */
	tags: InheritedConditionConfig | null;
	/** Condition that matches against a toolchain detected for a project. */
	toolchain?: InheritedConditionConfig | null;
	/** Condition that matches against a toolchain detected for a project. */
	toolchains: InheritedConditionConfig | null;
}

export type TaskOptionEnvFile = boolean | string | string[];

/** The strategy in which to merge a specific task option. */
export type TaskMergeStrategy = 'append' | 'prepend' | 'preserve' | 'replace';

/** The operating system in which to only run this task on. */
export type TaskOperatingSystem = 'linux' | 'macos' | 'windows';

/** The style in which task output will be printed to the console. */
export type TaskOutputStyle = 'buffer' | 'buffer-only-failure' | 'hash' | 'none' | 'stream';

/**
 * The priority levels a task can be bucketed into when running
 * in the action pipeline.
 */
export type TaskPriority = 'critical' | 'high' | 'normal' | 'low';

/** A list of available shells on Unix. */
export type TaskUnixShell =
	| 'bash'
	| 'elvish'
	| 'fish'
	| 'ion'
	| 'murex'
	| 'nu'
	| 'pwsh'
	| 'xonsh'
	| 'zsh';

/** A list of available shells on Windows. */
export type TaskWindowsShell = 'bash' | 'elvish' | 'fish' | 'murex' | 'nu' | 'pwsh' | 'xonsh';

/** Options to control task inheritance, execution, and more. */
export interface TaskOptionsConfig {
	/** The pattern in which affected files will be passed to the task. */
	affectedFiles: boolean | 'args' | 'env' | null;
	/**
	 * When affected and no files are matching, pass the task's inputs
	 * as arguments to the command, instead of `.`.
	 */
	affectedPassInputs: boolean | null;
	/**
	 * Allow the task to fail without failing the entire action pipeline.
	 * @since 1.13.0
	 */
	allowFailure: boolean | null;
	/**
	 * Cache the `outputs` of the task for incremental builds.
	 * Defaults to `true` if outputs are configured for the task.
	 */
	cache: boolean | 'local' | 'remote' | null;
	/**
	 * A custom key to include in the cache hashing process. Can be
	 * used to invalidate local and remote caches.
	 */
	cacheKey: string | null;
	/**
	 * Lifetime to cache the task itself, in the format of "1h", "30m", etc.
	 * If not defined, caches live forever, or until inputs change.
	 * @since 1.29.0
	 */
	cacheLifetime: string | null;
	/**
	 * Loads and sets environment variables from the `.env` file(s) when
	 * running the task.
	 */
	envFile: TaskOptionEnvFile | null;
	/**
	 * Automatically infer inputs from file groups or environment variables
	 * that were utilized within `command`, `script`, `args`, and `env`.
	 * @since 1.31.0
	 */
	inferInputs: boolean | null;
	/**
	 * Marks the task as interactive, so that it will run in isolation,
	 * and have direct access to stdin.
	 * @since 1.12.0
	 */
	interactive: boolean | null;
	/**
	 * Marks the task as internal, which disables it from being ran
	 * from the command line, but can still be depended on by other tasks.
	 * @since 1.23.0
	 */
	internal: boolean | null;
	/**
	 * The default strategy to use when merging `args`, `deps`, `env`,
	 * `inputs`, or `outputs` with an inherited task. Can be overridden
	 * with the other field-specific merge options.
	 *
	 * @default 'append'
	 */
	merge: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `args` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeArgs: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `deps` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeDeps: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `env` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeEnv: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `inputs` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeInputs: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `outputs` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeOutputs: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `toolchains` with an inherited task.
	 * @since 2.0.0
	 *
	 * @default 'append'
	 */
	mergeToolchains: TaskMergeStrategy | null;
	/**
	 * Creates an exclusive lock on a virtual resource, preventing other
	 * tasks using the same resource from running concurrently.
	 * @since 1.24.0
	 */
	mutex: string | null;
	/** The operating system in which to only run this task on. */
	os: TaskOperatingSystem | TaskOperatingSystem[] | null;
	/**
	 * The style in which task output will be printed to the console.
	 *
	 * @default 'buffer'
	 * @env MOON_OUTPUT_STYLE
	 */
	outputStyle: TaskOutputStyle | null;
	/**
	 * Marks the task as persistent (continuously running). This is ideal
	 * for watchers, servers, or never-ending processes.
	 * @since 1.6.0
	 */
	persistent: boolean | null;
	/**
	 * Marks the task with a certain priority, which determines the order
	 * in which it is ran within the action pipeline.
	 *
	 * @default 'normal'
	 */
	priority: TaskPriority | null;
	/**
	 * The number of times a failing task will be retried to succeed.
	 *
	 * @env MOON_RETRY_COUNT
	 */
	retryCount: number | null;
	/**
	 * Runs direct task dependencies (via `deps`) in sequential order.
	 * This _does not_ apply to indirect or transient dependencies.
	 */
	runDepsInParallel: boolean | null;
	/** Runs the task from the workspace root, instead of the project root. */
	runFromWorkspaceRoot: boolean | null;
	/**
	 * Whether to run the task in CI or not, when executing `moon ci`,
	 * `moon check`, or `moon run`.
	 */
	runInCI: boolean | 'always' | 'affected' | 'only' | 'skip' | null;
	/**
	 * Runs the task within a shell. When not defined, runs the task
	 * directly while relying on native `PATH` resolution.
	 */
	shell: boolean | null;
	/** The maximum time in seconds that a task can run before being cancelled. */
	timeout: number | null;
	/**
	 * The shell to run the task in when on a Unix-based machine.
	 * @since 1.21.0
	 *
	 * @default 'bash'
	 */
	unixShell: TaskUnixShell | null;
	/**
	 * The shell to run the task in when on a Windows machine.
	 * @since 1.21.0
	 *
	 * @default 'pwsh'
	 */
	windowsShell: TaskWindowsShell | null;
}

/** A file path output. */
export interface FileOutput {
	/** The literal file path. */
	file: string;
	/**
	 * Mark the file as optional instead of failing with
	 * an error after running a task and the output doesn't exist.
	 */
	optional?: boolean | null;
}

/** A glob pattern output. */
export interface GlobOutput {
	/** The glob pattern. */
	glob: string;
	/**
	 * Mark the file as optional instead of failing with
	 * an error after running a task and the output doesn't exist.
	 */
	optional?: boolean | null;
}

export type Output = string | FileOutput | GlobOutput;

/** Preset options to inherit. */
export type TaskPreset = 'utility' | 'server';

/** The type of task. */
export type TaskType = 'build' | 'run' | 'test';

/** Configures a task to be ran within the action pipeline. */
export interface TaskConfig {
	/**
	 * Arguments to pass to the command when it's ran. Can be
	 * defined as a string, or a list of individual arguments.
	 */
	args: TaskArgs;
	/**
	 * The command line to execute when the task is ran.
	 * Supports the command (executable) with or without arguments.
	 * Can be defined as a string, or a list of individual arguments.
	 */
	command: TaskArgs;
	/**
	 * Other tasks that this task depends on, and must run to completion
	 * before this task is ran. Can depend on sibling tasks, or tasks in
	 * other projects, using targets.
	 */
	dependsOn?: TaskDependency[] | null;
	/**
	 * Other tasks that this task depends on, and must run to completion
	 * before this task is ran. Can depend on sibling tasks, or tasks in
	 * other projects, using targets.
	 */
	deps: TaskDependency[] | null;
	/**
	 * A human-readable description about the task.
	 * @since 1.22.0
	 */
	description: string | null;
	/**
	 * A map of environment variables that will be set in the child
	 * process when the task is ran.
	 */
	env: Record<string, string | null> | null;
	/** Extends settings from a sibling task by identifier. */
	extends: Id | null;
	/**
	 * A list of inputs that will be hashing and compared against changed files
	 * to determine affected status. If affected, the task will run, otherwise
	 * it will exit early. An input can be a literal file path, a glob pattern,
	 * environment variable, and more.
	 *
	 * When not provided, all files within the project are considered inputs.
	 * When an empty list, no files are considered. Otherwise, an
	 * explicit list of inputs are considered.
	 */
	inputs: Input[] | null;
	/** Options to control task inheritance, execution, and more. */
	options: TaskOptionsConfig;
	/**
	 * A list of outputs that will be created when the task has successfully ran.
	 * An output can be a literal file path, or a glob pattern.
	 */
	outputs: Output[] | null;
	/** The preset to apply for the task. Will inherit default options. */
	preset: TaskPreset | null;
	/**
	 * A script to run within a shell. A script is anything from a single command,
	 * to multiple commands, or shell specific syntax. Does not support
	 * arguments, merging, or inheritance. This overrides `command` and `args`.
	 * @since 1.27.0
	 */
	script: string | null;
	/**
	 * A toolchain, or list of toolchains, in which the task will inherit
	 * functionality from.
	 */
	toolchain?: Id | Id[] | null;
	/**
	 * A toolchain, or list of toolchains, in which the task will inherit
	 * functionality from.
	 */
	toolchains: Id | Id[] | null;
	/**
	 * The type of task, primarily used for categorical reasons. When not provided,
	 * will be automatically determined based on configured outputs.
	 *
	 * @default 'test'
	 */
	type: TaskType | null;
}

/**
 * Configures tasks and task related settings that'll be inherited by all
 * matching projects.
 * Docs: https://moonrepo.dev/docs/config/tasks
 */
export interface InheritedTasksConfig {
	/** @default './cache/schemas/tasks.json' */
	$schema?: string;
	/**
	 * Extends one or many tasks configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends: ExtendsFrom | null;
	/**
	 * A map of group identifiers to a list of file paths, globs, and
	 * environment variables, that can be referenced from tasks.
	 */
	fileGroups: Record<Id, Input[]>;
	/**
	 * Task dependencies (`deps`) that will be automatically injected into every
	 * task that inherits this configuration.
	 */
	implicitDeps: TaskDependency[];
	/**
	 * Task inputs (`inputs`) that will be automatically injected into every
	 * task that inherits this configuration.
	 */
	implicitInputs: Input[];
	/**
	 * A map of conditions that define which projects will inherit these
	 * tasks and configuration. If not defined, will be inherited by all projects.
	 * @since 2.0.0
	 */
	inheritedBy: InheritedByConfig | null;
	/**
	 * Default task options for all inherited tasks.
	 * @since 1.20.0
	 */
	taskOptions: TaskOptionsConfig | null;
	/**
	 * A map of identifiers to task objects. Tasks represent the work-unit
	 * of a project, and can be ran in the action pipeline.
	 */
	tasks: Record<Id, TaskConfig>;
}

export type PartialTaskArgs = null | string | string[];

/** Expanded information about a task dependency. */
export interface PartialTaskDependencyConfig {
	/** Additional arguments to pass to this dependency when it's ran. */
	args?: PartialTaskArgs | null;
	/** A map of environment variables specific to this dependency. */
	env?: Record<string, string | null> | null;
	/**
	 * Marks the dependency as optional when being inherited from the top-level.
	 * @since 1.20.0
	 */
	optional?: boolean | null;
	/** The target of the depended on task. */
	target?: string | null;
}

export type PartialTaskDependency = string | PartialTaskDependencyConfig;

/**
 * A condition that utilizes a combination of logical operators
 * to match against. When matching, all clauses must be satisfied.
 */
export interface PartialInheritedClauseConfig {
	/** Require all values to match, using an AND operator. */
	and?: Id | Id[] | null;
	/** Require no values to match, using a NOT operator. */
	not?: Id | Id[] | null;
	/** Require any values to match, using an OR operator. */
	or?: Id | Id[] | null;
}

export type PartialInheritedConditionConfig = Id | Id[] | PartialInheritedClauseConfig;

/**
 * Configures conditions that must match against a project for tasks
 * to be inherited. If multiple conditions are defined, then all must match
 * for inheritance to occur. If no conditions are defined, then tasks will
 * be inherited by all projects.
 */
export interface PartialInheritedByConfig {
	/**
	 * Condition that matches against literal files within a project.
	 * If multiple values are provided, at least 1 file needs to exist.
	 */
	file?: string | string[] | null;
	/**
	 * Condition that matches against literal files within a project.
	 * If multiple values are provided, at least 1 file needs to exist.
	 */
	files?: string | string[] | null;
	/**
	 * Condition that matches against a project's `language`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	language?: LanguageType | LanguageType[] | null;
	/**
	 * Condition that matches against a project's `language`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	languages?: LanguageType | LanguageType[] | null;
	/**
	 * Condition that matches against a project's `layer`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	layer?: LayerType | LayerType[] | null;
	/**
	 * Condition that matches against a project's `layer`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	layers?: LayerType | LayerType[] | null;
	/**
	 * The order in which this configuration is inherited by a project.
	 * Lower is inherited first, while higher is last.
	 */
	order?: number | null;
	/**
	 * Condition that matches against a project's `stack`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	stack?: StackType | StackType[] | null;
	/**
	 * Condition that matches against a project's `stack`.
	 * If multiple values are provided, it matches using an OR operator.
	 *
	 * @default 'unknown'
	 */
	stacks?: StackType | StackType[] | null;
	/** Condition that matches against a tag within the project. */
	tag?: PartialInheritedConditionConfig | null;
	/** Condition that matches against a tag within the project. */
	tags?: PartialInheritedConditionConfig | null;
	/** Condition that matches against a toolchain detected for a project. */
	toolchain?: PartialInheritedConditionConfig | null;
	/** Condition that matches against a toolchain detected for a project. */
	toolchains?: PartialInheritedConditionConfig | null;
}

/** Options to control task inheritance, execution, and more. */
export interface PartialTaskOptionsConfig {
	/** The pattern in which affected files will be passed to the task. */
	affectedFiles?: boolean | 'args' | 'env' | null;
	/**
	 * When affected and no files are matching, pass the task's inputs
	 * as arguments to the command, instead of `.`.
	 */
	affectedPassInputs?: boolean | null;
	/**
	 * Allow the task to fail without failing the entire action pipeline.
	 * @since 1.13.0
	 */
	allowFailure?: boolean | null;
	/**
	 * Cache the `outputs` of the task for incremental builds.
	 * Defaults to `true` if outputs are configured for the task.
	 */
	cache?: boolean | 'local' | 'remote' | null;
	/**
	 * A custom key to include in the cache hashing process. Can be
	 * used to invalidate local and remote caches.
	 */
	cacheKey?: string | null;
	/**
	 * Lifetime to cache the task itself, in the format of "1h", "30m", etc.
	 * If not defined, caches live forever, or until inputs change.
	 * @since 1.29.0
	 */
	cacheLifetime?: string | null;
	/**
	 * Loads and sets environment variables from the `.env` file(s) when
	 * running the task.
	 */
	envFile?: TaskOptionEnvFile | null;
	/**
	 * Automatically infer inputs from file groups or environment variables
	 * that were utilized within `command`, `script`, `args`, and `env`.
	 * @since 1.31.0
	 */
	inferInputs?: boolean | null;
	/**
	 * Marks the task as interactive, so that it will run in isolation,
	 * and have direct access to stdin.
	 * @since 1.12.0
	 */
	interactive?: boolean | null;
	/**
	 * Marks the task as internal, which disables it from being ran
	 * from the command line, but can still be depended on by other tasks.
	 * @since 1.23.0
	 */
	internal?: boolean | null;
	/**
	 * The default strategy to use when merging `args`, `deps`, `env`,
	 * `inputs`, or `outputs` with an inherited task. Can be overridden
	 * with the other field-specific merge options.
	 *
	 * @default 'append'
	 */
	merge?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `args` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeArgs?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `deps` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeDeps?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `env` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeEnv?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `inputs` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeInputs?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `outputs` with an inherited task.
	 *
	 * @default 'append'
	 */
	mergeOutputs?: TaskMergeStrategy | null;
	/**
	 * The strategy to use when merging `toolchains` with an inherited task.
	 * @since 2.0.0
	 *
	 * @default 'append'
	 */
	mergeToolchains?: TaskMergeStrategy | null;
	/**
	 * Creates an exclusive lock on a virtual resource, preventing other
	 * tasks using the same resource from running concurrently.
	 * @since 1.24.0
	 */
	mutex?: string | null;
	/** The operating system in which to only run this task on. */
	os?: TaskOperatingSystem | TaskOperatingSystem[] | null;
	/**
	 * The style in which task output will be printed to the console.
	 *
	 * @default 'buffer'
	 * @env MOON_OUTPUT_STYLE
	 */
	outputStyle?: TaskOutputStyle | null;
	/**
	 * Marks the task as persistent (continuously running). This is ideal
	 * for watchers, servers, or never-ending processes.
	 * @since 1.6.0
	 */
	persistent?: boolean | null;
	/**
	 * Marks the task with a certain priority, which determines the order
	 * in which it is ran within the action pipeline.
	 *
	 * @default 'normal'
	 */
	priority?: TaskPriority | null;
	/**
	 * The number of times a failing task will be retried to succeed.
	 *
	 * @env MOON_RETRY_COUNT
	 */
	retryCount?: number | null;
	/**
	 * Runs direct task dependencies (via `deps`) in sequential order.
	 * This _does not_ apply to indirect or transient dependencies.
	 */
	runDepsInParallel?: boolean | null;
	/** Runs the task from the workspace root, instead of the project root. */
	runFromWorkspaceRoot?: boolean | null;
	/**
	 * Whether to run the task in CI or not, when executing `moon ci`,
	 * `moon check`, or `moon run`.
	 */
	runInCI?: boolean | 'always' | 'affected' | 'only' | 'skip' | null;
	/**
	 * Runs the task within a shell. When not defined, runs the task
	 * directly while relying on native `PATH` resolution.
	 */
	shell?: boolean | null;
	/** The maximum time in seconds that a task can run before being cancelled. */
	timeout?: number | null;
	/**
	 * The shell to run the task in when on a Unix-based machine.
	 * @since 1.21.0
	 *
	 * @default 'bash'
	 */
	unixShell?: TaskUnixShell | null;
	/**
	 * The shell to run the task in when on a Windows machine.
	 * @since 1.21.0
	 *
	 * @default 'pwsh'
	 */
	windowsShell?: TaskWindowsShell | null;
}

/** Configures a task to be ran within the action pipeline. */
export interface PartialTaskConfig {
	/**
	 * Arguments to pass to the command when it's ran. Can be
	 * defined as a string, or a list of individual arguments.
	 */
	args?: PartialTaskArgs | null;
	/**
	 * The command line to execute when the task is ran.
	 * Supports the command (executable) with or without arguments.
	 * Can be defined as a string, or a list of individual arguments.
	 */
	command?: PartialTaskArgs | null;
	/**
	 * Other tasks that this task depends on, and must run to completion
	 * before this task is ran. Can depend on sibling tasks, or tasks in
	 * other projects, using targets.
	 */
	dependsOn?: PartialTaskDependency[] | null;
	/**
	 * Other tasks that this task depends on, and must run to completion
	 * before this task is ran. Can depend on sibling tasks, or tasks in
	 * other projects, using targets.
	 */
	deps?: PartialTaskDependency[] | null;
	/**
	 * A human-readable description about the task.
	 * @since 1.22.0
	 */
	description?: string | null;
	/**
	 * A map of environment variables that will be set in the child
	 * process when the task is ran.
	 */
	env?: Record<string, string | null> | null;
	/** Extends settings from a sibling task by identifier. */
	extends?: Id | null;
	/**
	 * A list of inputs that will be hashing and compared against changed files
	 * to determine affected status. If affected, the task will run, otherwise
	 * it will exit early. An input can be a literal file path, a glob pattern,
	 * environment variable, and more.
	 *
	 * When not provided, all files within the project are considered inputs.
	 * When an empty list, no files are considered. Otherwise, an
	 * explicit list of inputs are considered.
	 */
	inputs?: Input[] | null;
	/** Options to control task inheritance, execution, and more. */
	options?: PartialTaskOptionsConfig | null;
	/**
	 * A list of outputs that will be created when the task has successfully ran.
	 * An output can be a literal file path, or a glob pattern.
	 */
	outputs?: Output[] | null;
	/** The preset to apply for the task. Will inherit default options. */
	preset?: TaskPreset | null;
	/**
	 * A script to run within a shell. A script is anything from a single command,
	 * to multiple commands, or shell specific syntax. Does not support
	 * arguments, merging, or inheritance. This overrides `command` and `args`.
	 * @since 1.27.0
	 */
	script?: string | null;
	/**
	 * A toolchain, or list of toolchains, in which the task will inherit
	 * functionality from.
	 */
	toolchain?: Id | Id[] | null;
	/**
	 * A toolchain, or list of toolchains, in which the task will inherit
	 * functionality from.
	 */
	toolchains?: Id | Id[] | null;
	/**
	 * The type of task, primarily used for categorical reasons. When not provided,
	 * will be automatically determined based on configured outputs.
	 *
	 * @default 'test'
	 */
	type?: TaskType | null;
}

/**
 * Configures tasks and task related settings that'll be inherited by all
 * matching projects.
 * Docs: https://moonrepo.dev/docs/config/tasks
 */
export interface PartialInheritedTasksConfig {
	/** @default './cache/schemas/tasks.json' */
	$schema?: string | null;
	/**
	 * Extends one or many tasks configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends?: ExtendsFrom | null;
	/**
	 * A map of group identifiers to a list of file paths, globs, and
	 * environment variables, that can be referenced from tasks.
	 */
	fileGroups?: Record<Id, Input[]> | null;
	/**
	 * Task dependencies (`deps`) that will be automatically injected into every
	 * task that inherits this configuration.
	 */
	implicitDeps?: PartialTaskDependency[] | null;
	/**
	 * Task inputs (`inputs`) that will be automatically injected into every
	 * task that inherits this configuration.
	 */
	implicitInputs?: Input[] | null;
	/**
	 * A map of conditions that define which projects will inherit these
	 * tasks and configuration. If not defined, will be inherited by all projects.
	 * @since 2.0.0
	 */
	inheritedBy?: PartialInheritedByConfig | null;
	/**
	 * Default task options for all inherited tasks.
	 * @since 1.20.0
	 */
	taskOptions?: PartialTaskOptionsConfig | null;
	/**
	 * A map of identifiers to task objects. Tasks represent the work-unit
	 * of a project, and can be ran in the action pipeline.
	 */
	tasks?: Record<Id, PartialTaskConfig> | null;
}
