// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

export interface PartialTemplateVariableBoolSetting {
	default?: boolean | null;
	prompt?: string | null;
	required?: boolean | null;
	type?: 'boolean' | null;
}

export interface PartialTemplateVariableEnumValueConfig {
	label?: string | null;
	value?: string | null;
}

export type PartialTemplateVariableEnumValue = string | PartialTemplateVariableEnumValueConfig;

export interface PartialTemplateVariableEnumSetting {
	default?: string | null;
	multiple?: boolean | null;
	prompt?: string | null;
	type?: 'enum' | null;
	values?: PartialTemplateVariableEnumValue[] | null;
}

export interface PartialTemplateVariableNumberSetting {
	default?: number | null;
	prompt?: string | null;
	required?: boolean | null;
	type?: 'number' | null;
}

export interface PartialTemplateVariableStringSetting {
	default?: string | null;
	prompt?: string | null;
	required?: boolean | null;
	type?: 'string' | null;
}

export type PartialTemplateVariable =
	| PartialTemplateVariableBoolSetting
	| PartialTemplateVariableEnumSetting
	| PartialTemplateVariableNumberSetting
	| PartialTemplateVariableStringSetting;

/** Docs: https://moonrepo.dev/docs/config/template */
export interface PartialTemplateConfig {
	/** @default 'https://moonrepo.dev/schemas/template.json' */
	$schema?: string | null;
	description?: string | null;
	destination?: string | null;
	title?: string | null;
	variables?: Record<string, PartialTemplateVariable> | null;
}

/** Docs: https://moonrepo.dev/docs/config/template#frontmatter */
export interface PartialTemplateFrontmatterConfig {
	/** @default 'https://moonrepo.dev/schemas/template-frontmatter.json' */
	$schema?: string | null;
	force?: boolean | null;
	skip?: boolean | null;
	to?: string | null;
}

export interface TemplateVariableBoolSetting {
	default: boolean;
	prompt: string | null;
	required: boolean | null;
	type: 'boolean';
}

export interface TemplateVariableEnumValueConfig {
	label: string;
	value: string;
}

export type TemplateVariableEnumValue = string | TemplateVariableEnumValueConfig;

export interface TemplateVariableEnumSetting {
	default: string;
	multiple: boolean | null;
	prompt: string;
	type: 'enum';
	values: TemplateVariableEnumValue[];
}

export interface TemplateVariableNumberSetting {
	default: number;
	prompt: string | null;
	required: boolean | null;
	type: 'number';
}

export interface TemplateVariableStringSetting {
	default: string;
	prompt: string | null;
	required: boolean | null;
	type: 'string';
}

export type TemplateVariable =
	| TemplateVariableBoolSetting
	| TemplateVariableEnumSetting
	| TemplateVariableNumberSetting
	| TemplateVariableStringSetting;

/** Docs: https://moonrepo.dev/docs/config/template */
export interface TemplateConfig {
	/** @default 'https://moonrepo.dev/schemas/template.json' */
	$schema: string;
	description: string;
	destination: string | null;
	title: string;
	variables: Record<string, TemplateVariable>;
}

/** Docs: https://moonrepo.dev/docs/config/template#frontmatter */
export interface TemplateFrontmatterConfig {
	/** @default 'https://moonrepo.dev/schemas/template-frontmatter.json' */
	$schema: string;
	force: boolean;
	skip: boolean;
	to: string | null;
}
