// Automatically generated by schematic. DO NOT MODIFY!

 

import type { ExtendsFrom, Id } from './common';

/** Configures how and where moon updates will be received. */
export interface MoonConfig {
	/**
	 * A secure URL for downloading the moon binary itself.
	 *
	 * @default 'https://github.com/moonrepo/moon/releases/latest/download'
	 */
	downloadUrl?: string;
	/**
	 * A secure URL to lookup the latest available version.
	 *
	 * @default 'https://launch.moonrepo.app/moon/check_version'
	 */
	manifestUrl?: string;
}

export type PluginLocator = string;

export type UnresolvedVersionSpec = string;

export type ToolchainPluginVersionFrom = boolean | string;

/** Configures an individual toolchain. */
export interface ToolchainPluginConfig {
	/** Arbitrary configuration that'll be passed to the WASM plugin. */
	config: Record<string, unknown>;
	/** Location of the WASM plugin to use. */
	plugin: PluginLocator | null;
	/** The version of the toolchain to download and install. */
	version: UnresolvedVersionSpec | null;
	/**
	 * Inherit the version from the root `.prototools`.
	 * When true, matches using the same identifier, otherwise a
	 * string can be provided for a custom identifier.
	 */
	versionFromPrototools: ToolchainPluginVersionFrom;
}

export type VersionSpec = string;

/** Configures how moon integrates with proto. */
export interface ProtoConfig {
	/**
	 * The version of proto to download and install,
	 * and to use for installing and running other toolchains.
	 */
	version?: VersionSpec;
}

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export interface ToolchainsConfig {
	/** @default 'https://moonrepo.dev/schemas/toolchain.json' */
	$schema?: string;
	/**
	 * Extends one or many toolchain configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends: ExtendsFrom | null;
	/** Configures moon itself. */
	moon: MoonConfig;
	/**
	 * Configures and integrates toolchains into the system using
	 * a unique identifier.
	 */
	plugins: Record<Id, ToolchainPluginConfig>;
	/** Configures how moon integrates with proto. */
	proto: ProtoConfig;
}

/** Configures how and where moon updates will be received. */
export interface PartialMoonConfig {
	/**
	 * A secure URL for downloading the moon binary itself.
	 *
	 * @default 'https://github.com/moonrepo/moon/releases/latest/download'
	 */
	downloadUrl?: string | null;
	/**
	 * A secure URL to lookup the latest available version.
	 *
	 * @default 'https://launch.moonrepo.app/moon/check_version'
	 */
	manifestUrl?: string | null;
}

/** Configures an individual toolchain. */
export interface PartialToolchainPluginConfig {
	/** Arbitrary configuration that'll be passed to the WASM plugin. */
	config?: Record<string, unknown> | null;
	/** Location of the WASM plugin to use. */
	plugin?: PluginLocator | null;
	/** The version of the toolchain to download and install. */
	version?: UnresolvedVersionSpec | null;
	/**
	 * Inherit the version from the root `.prototools`.
	 * When true, matches using the same identifier, otherwise a
	 * string can be provided for a custom identifier.
	 */
	versionFromPrototools?: ToolchainPluginVersionFrom | null;
}

/** Configures how moon integrates with proto. */
export interface PartialProtoConfig {
	/**
	 * The version of proto to download and install,
	 * and to use for installing and running other toolchains.
	 */
	version?: VersionSpec | null;
}

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export interface PartialToolchainsConfig {
	/** @default 'https://moonrepo.dev/schemas/toolchain.json' */
	$schema?: string | null;
	/**
	 * Extends one or many toolchain configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends?: ExtendsFrom | null;
	/** Configures moon itself. */
	moon?: PartialMoonConfig | null;
	/**
	 * Configures and integrates toolchains into the system using
	 * a unique identifier.
	 */
	plugins?: Record<Id, PartialToolchainPluginConfig> | null;
	/** Configures how moon integrates with proto. */
	proto?: PartialProtoConfig | null;
}
