// Automatically generated by schematic. DO NOT MODIFY!

 

import type { ExtendsFrom, Id } from './common';

/** Configures how and where moon updates will be received. */
export interface MoonConfig {
	/**
	 * A secure URL for downloading the moon binary itself.
	 *
	 * @default 'https://github.com/moonrepo/moon/releases/latest/download/{file}'
	 */
	downloadUrl?: string;
	/**
	 * A secure URL to lookup the latest available version.
	 *
	 * @default 'https://launch.moonrepo.app/moon/check_version'
	 */
	manifestUrl?: string;
}

export type PluginLocator = string;

export type UnresolvedVersionSpec = string;

export type ToolchainPluginVersionFrom = boolean | string;

export type ToolchainPluginConfigConfig = Record<string, unknown>;

/** Configures an individual toolchain. */
export interface ToolchainPluginConfigBase {
	/** Location of the WASM plugin to use. */
	plugin?: PluginLocator | null;
	/** The version of the toolchain to download and install. */
	version?: UnresolvedVersionSpec | null;
	/**
	 * Inherit the version from the root `.prototools`.
	 * When true, matches using the same identifier, otherwise a
	 * string can be provided for a custom identifier.
	 */
	versionFromPrototools: ToolchainPluginVersionFrom;
}

/** Configures an individual toolchain. */
export type ToolchainPluginConfig = ToolchainPluginConfigBase & ToolchainPluginConfigConfig;

export type VersionSpec = string;

/** Configures how moon integrates with proto. */
export interface ProtoConfig {
	/**
	 * The version of proto to download and install,
	 * and to use for installing and running other toolchains.
	 */
	version?: VersionSpec;
}

export type ToolchainsConfigPlugins = Record<Id, ToolchainPluginConfig>;

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export interface ToolchainsConfigBase {
	/** @default './cache/schemas/toolchains.json' */
	$schema?: string;
	/**
	 * Extends one or many toolchain configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends?: ExtendsFrom | null;
	/** Configures moon itself. */
	moon: MoonConfig;
	/** Configures how moon integrates with proto. */
	proto: ProtoConfig;
}

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export type ToolchainsConfig = ToolchainsConfigBase & ToolchainsConfigPlugins;

/** Configures how and where moon updates will be received. */
export interface PartialMoonConfig {
	/**
	 * A secure URL for downloading the moon binary itself.
	 *
	 * @default 'https://github.com/moonrepo/moon/releases/latest/download/{file}'
	 */
	downloadUrl?: string | null;
	/**
	 * A secure URL to lookup the latest available version.
	 *
	 * @default 'https://launch.moonrepo.app/moon/check_version'
	 */
	manifestUrl?: string | null;
}

export type PartialToolchainPluginConfigConfig = Record<string, unknown>;

/** Configures an individual toolchain. */
export interface PartialToolchainPluginConfigBase {
	/** Location of the WASM plugin to use. */
	plugin?: PluginLocator | null;
	/** The version of the toolchain to download and install. */
	version?: UnresolvedVersionSpec | null;
	/**
	 * Inherit the version from the root `.prototools`.
	 * When true, matches using the same identifier, otherwise a
	 * string can be provided for a custom identifier.
	 */
	versionFromPrototools?: ToolchainPluginVersionFrom | null;
}

/** Configures an individual toolchain. */
export type PartialToolchainPluginConfig = PartialToolchainPluginConfigBase &
	PartialToolchainPluginConfigConfig;

/** Configures how moon integrates with proto. */
export interface PartialProtoConfig {
	/**
	 * The version of proto to download and install,
	 * and to use for installing and running other toolchains.
	 */
	version?: VersionSpec | null;
}

export type PartialToolchainsConfigPlugins = Record<Id, PartialToolchainPluginConfig>;

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export interface PartialToolchainsConfigBase {
	/** @default './cache/schemas/toolchains.json' */
	$schema?: string | null;
	/**
	 * Extends one or many toolchain configuration files.
	 * Supports a relative file path or a secure URL.
	 * @since 1.12.0
	 */
	extends?: ExtendsFrom | null;
	/** Configures moon itself. */
	moon?: PartialMoonConfig | null;
	/** Configures how moon integrates with proto. */
	proto?: PartialProtoConfig | null;
}

/**
 * Configures all toolchains.
 * Docs: https://moonrepo.dev/docs/config/toolchain
 */
export type PartialToolchainsConfig = PartialToolchainsConfigBase & PartialToolchainsConfigPlugins;
