// Automatically generated by schematic. DO NOT MODIFY!

/* eslint-disable */

export type CodeownersOrderBy = 'file-source' | 'project-name';

export type HasherOptimization = 'accuracy' | 'performance';

export type HasherWalkStrategy = 'glob' | 'vcs';

export type VcsManager = 'git' | 'svn';

export type VcsProvider = 'bitbucket' | 'github' | 'gitlab' | 'other';

export interface CodeownersConfig {
	globalPaths: Record<string, string[]>;
	orderBy: CodeownersOrderBy;
	syncOnRun: boolean;
}

export interface PartialCodeownersConfig {
	globalPaths?: Record<string, string[]> | null;
	orderBy?: CodeownersOrderBy | null;
	syncOnRun?: boolean | null;
}

export interface ConstraintsConfig {
	enforceProjectTypeRelationships: boolean;
	tagRelationships: Record<Id, Id[]>;
}

export interface PartialConstraintsConfig {
	enforceProjectTypeRelationships?: boolean | null;
	tagRelationships?: Record<Id, Id[]> | null;
}

export interface GeneratorConfig {
	templates: FilePath[];
}

export interface PartialGeneratorConfig {
	templates?: FilePath[] | null;
}

export interface HasherConfig {
	batchSize: number;
	optimization: HasherOptimization;
	walkStrategy: HasherWalkStrategy;
	warnOnMissingInputs: boolean;
}

export interface PartialHasherConfig {
	batchSize?: number | null;
	optimization?: HasherOptimization | null;
	walkStrategy?: HasherWalkStrategy | null;
	warnOnMissingInputs?: boolean | null;
}

export interface NotifierConfig {
	webhookUrl: string | null;
}

export interface PartialNotifierConfig {
	webhookUrl?: string | null;
}

export interface RunnerConfig {
	archivableTargets: Target[];
	cacheLifetime: string;
	inheritColorsForPipedTasks: boolean;
	logRunningCommand: boolean;
}

export interface PartialRunnerConfig {
	archivableTargets?: Target[] | null;
	cacheLifetime?: string | null;
	inheritColorsForPipedTasks?: boolean | null;
	logRunningCommand?: boolean | null;
}

export interface VcsConfig {
	defaultBranch: string;
	manager: VcsManager;
	provider: VcsProvider;
	remoteCandidates: string[];
}

export interface PartialVcsConfig {
	defaultBranch?: string | null;
	manager?: VcsManager | null;
	provider?: VcsProvider | null;
	remoteCandidates?: string[] | null;
}

export interface WorkspaceConfig {
	$schema: string;
	codeowners: CodeownersConfig;
	constraints: ConstraintsConfig;
	extends: string | null;
	generator: GeneratorConfig;
	hasher: HasherConfig;
	notifier: NotifierConfig;
	projects: WorkspaceProjects;
	runner: RunnerConfig;
	telemetry: boolean;
	vcs: VcsConfig;
	versionConstraint: string | null;
}

export interface PartialWorkspaceConfig {
	$schema?: string | null;
	codeowners?: CodeownersConfig | null;
	constraints?: ConstraintsConfig | null;
	extends?: string | null;
	generator?: GeneratorConfig | null;
	hasher?: HasherConfig | null;
	notifier?: NotifierConfig | null;
	projects?: WorkspaceProjects | null;
	runner?: RunnerConfig | null;
	telemetry?: boolean | null;
	vcs?: VcsConfig | null;
	versionConstraint?: string | null;
}