[package]
name = "moon_node_platform"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_action = { path = "../../../crates/action" }
moon_action_context = { path = "../../../crates/action-context" }
moon_common = { path = "../../../crates/common" }
moon_config = { path = "../../../crates/config" }
moon_console = { path = "../../../crates/console" }
moon_hash = { path = "../../../crates/hash" }
moon_javascript_platform = { path = "../../javascript/platform" }
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_node_lang = { path = "../lang" }
moon_node_tool = { path = "../tool" }
moon_platform = { path = "../../core/platform" }
moon_process = { path = "../../../crates/process" }
moon_project = { path = "../../../crates/project" }
moon_task = { path = "../../../crates/task" }
moon_tool = { path = "../../core/tool" }
moon_utils = { path = "../../core/utils" }
miette = { workspace = true }
proto_core = { workspace = true }
rustc-hash = { workspace = true }
schematic = { workspace = true, features = ["config"] }
serde = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true, features = ["glob"] }
tracing = { workspace = true }

[lints]
workspace = true
