[package]
name = "moon_project_graph"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Project graph for moon represented as a DAG."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_common = { path = "../common" }
moon_config = { path = "../config" }
moon_graph_utils = { path = "../graph-utils" }
moon_project = { path = "../project" }
moon_project_expander = { path = "../project-expander" }
moon_task = { path = "../task" }
miette = { workspace = true }
petgraph = { workspace = true }
rustc-hash = { workspace = true }
scc = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
moon_cache = { path = "../cache" }
moon_test_utils2 = { path = "../test-utils" }
moon_query = { path = "../query" }
moon_workspace = { path = "../workspace" }
starbase_events = { workspace = true }
starbase_sandbox = { workspace = true }
starbase_utils = { workspace = true, features = ["json"] }
tokio = { workspace = true }

[lints]
workspace = true
