$schema: '../cache/schemas/tasks.json'

inheritedBy:
  toolchains: 'node'

implicitDeps:
  - '^:build'

fileGroups:
  configs:
    - '*.{js,json}'
  sources:
    - 'src/**/*'
    - 'types/**/*'
  tests:
    - 'tests/**/*'

tasks:
  build:
    command: 'vp pack'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.json'
      - '/tsconfig.options.json'
      - '/vite.config.ts'
    outputs:
      - 'cjs'

  test:
    command: 'vp test run --passWithNoTests'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '/vite.config.ts'

  typecheck:
    command: 'tsc --build'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - 'tsconfig.json'
      - '/tsconfig.options.json'
