{%- if minimal -%}

bun:
{%- if bun_version != "" %}
  version: '{{ bun_version }}'
{%- else %}
  version: '1.0.0'
{%- endif %}

{%- else -%}

bun:
{%- if bun_version != "" %}
  version: '{{ bun_version }}'
{%- else %}
  # version: '1.0.0'
{%- endif %}
  # dependencyVersionFormat: 'workspace'
  # rootPackageOnly: true
  syncProjectWorkspaceDependencies: {{ sync_dependencies }}

{%- endif %}
