{%- if minimal -%}

node:
{%- if node_version is defined %}
  version: '{{ node_version }}'
{%- else %}
  version: '20.0.0'
{%- endif %}
  packageManager: '{{ package_manager }}'
{%- if package_manager_version is defined %}
  {{ package_manager }}:
    version: '{{ package_manager_version }}'
{%- endif %}

{%- else -%}

node:
{%- if node_version is defined %}
  version: '{{ node_version }}'
{%- else %}
  # version: '20.0.0'
{%- endif %}
  packageManager: '{{ package_manager }}'
{%- if package_manager_version is defined %}
  {{ package_manager }}:
    version: '{{ package_manager_version }}'
{%- else %}
  {{ package_manager }}: {}
{%- endif %}
  addEnginesConstraint: true
  dedupeOnLockfileChange: {{ dedupe_lockfile }}
  # dependencyVersionFormat: 'workspace'
  inferTasksFromScripts: {{ infer_tasks }}
  # rootPackageOnly: true
  syncProjectWorkspaceDependencies: {{ sync_dependencies }}
{%- if node_version_manager == "nvm" %}
  syncVersionManagerConfig: 'nvm'
{%- elif node_version_manager == "nodenv" %}
  syncVersionManagerConfig: 'nodenv'
{%- else %}
  # syncVersionManagerConfig: 'nvm'
{%- endif %}

{%- endif %}
