{%- if minimal -%}

rust:
{%- if rust_version is defined %}
  version: '{{ rust_version }}'
{%- else %}
  # version: 'stable'
{%- endif %}

{%- else -%}

rust:
{%- if rust_version is defined %}
  version: '{{ rust_version }}'
{%- else %}
  # version: 'stable'
{%- endif %}
  bins: []
  components: []
  syncToolchainConfig: false
  targets: []

{%- endif %}
