# https://moonrepo.dev/docs/config/workspace
$schema: './cache/schemas/workspace.json'

# extends: './shared/workspace.yml'

projects:
{%- for glob in project_globs | sort %}
  - '{{ glob }}'
{%- endfor %}
{%- for id, source in projects %}
  {{ id }}: '{{ source }}'
{%- endfor -%}

{% if vcs_manager != "git" or vcs_default_branch != "master" %}
vcs:
  manager: '{{ vcs_manager }}'
{%- if vcs_provider != "github" %}
  provider: '{{ vcs_provider }}'
{%- endif %}
  defaultBranch: '{{ vcs_default_branch }}'
{%- endif %}
