[package]
name = "moon_manifest"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Cache manifests."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_action = { path = "../action" }
moon_common = { path = "../common" }
moon_blob = { path = "../blob" }
moon_hash = { path = "../hash" }
bazel-remote-apis = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
miette = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["glob", "json"] }
thiserror ={ workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
