[package]
name = "moon_feature_flags"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Manages feature flags."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
starbase_utils = { workspace = true, features = ["glob", "glob-cache"] }

[lints]
workspace = true
