#!/usr/bin/env bash
set -eo pipefail

echo $@

for (( i=0; i <= $#; i++ )); do
  declare -x "ARG$i"="${!i}"
done

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

echo $ARG1 $ARG2 $ARG3

