[package]
name = "moon_node_lang"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
moon_bun_lang = { path = "../../bun/lang" }
moon_lang = { path = "../../core/lang" }
moon_logger = { path = "../../core/logger" }
moon_utils = { path = "../../core/utils" }
cached = { workspace = true }
miette = { workspace = true }
nodejs_package_json = "0.3.1"
package-lock-json-parser = "0.4.0"
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_yml = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true, features = [
	"editor-config",
	"json",
	"yaml",
] }
tracing = { workspace = true }
yarn-lock-parser = "0.11.0"

[dev-dependencies]
moon_test_utils = { path = "../../core/test-utils" }
reqwest = { workspace = true, features = ["blocking"] }

[lints]
workspace = true
