[package]
name = "moon_platform"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
moon_action = { path = "../../../crates/action" }
moon_action_context = { path = "../../../crates/action-context" }
moon_common = { path = "../../../crates/common" }
moon_config = { path = "../../../crates/config" }
moon_hash = { path = "../../../crates/hash" }
moon_process = { path = "../../../crates/process" }
moon_project = { path = "../../../crates/project" }
moon_task = { path = "../../../crates/task" }
moon_tool = { path = "../tool" }
moon_toolchain = { path = "../../../crates/toolchain" }
async-trait = { workspace = true }
miette = { workspace = true }
rustc-hash = { workspace = true }

[lints]
workspace = true
