name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .cargo/config.toml
      - .github/workflows/codspeed.yml
      - crates/**
      - legacy/**
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  codspeed:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-codspeed
          cache: false

      - name: Build the benchmark targets
        run: cargo codspeed build -p moon_affected -p moon_workspace

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
