name: Nix

on:
  push:
    branches:
      - master
    paths:
      - flake.nix
      - flake.lock
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - crates/**
  pull_request:
    paths:
      - flake.nix
      - flake.lock
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - crates/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Check flake
        run: nix flake check --no-build
      - name: Build package
        run: nix build .#default
